### ISSUE TITLE
Ergänzung von `educationalLevel`

### ISSUE THREAD

**Issue by oellers** [dini-ag-kim/amb#107]
Die Zielgruppe (audience) erfasst die Gruppe der Lernenden, jedoch nicht die Verortung des Lernenden in der Aus-/Fort-/Weiterbildung, in welchem eine Ressource genutzt werden kann.

**Vorgeschlagenes Feld:** [educationalLevel](https://schema.org/educationalLevel) (schema.org) 

**Gemappte Vergleichsübersicht:**
| [WLO-educationalContext](http://w3id.org/openeduhub/vocabs/educationalContext/) | [ComeIn-educationalLevel](http://w3id.org/comein/vocabs/educationalLevel-ComeIn/) | [ISCED-P & ISCED-A](http://uis.unesco.org/sites/default/files/documents/international-standard-classification-of-education-isced-2011-en.pdf) | [LOM-CH v2.1-educational level](https://www.educa.ch/sites/default/files/2020-11/applikationsprofil-lom-ch-v2.1-de.pdf) | [WLO-educationalLevel](http://w3id.org/openeduhub/vocabs/educationalLevel/) |
| -------- | -------- | -------- | -------- |-------- |
| Elementarbereich     |  Elementarbereich | 0 |  Frühbereich |   |
| Primarstufe      | Primarbereich | 1 |  Obligatorische Schule | 1 - 4 | 
| Sekundarstufe I      | Sekundarbereich I | 2 |   Obligatorische Schule | 5 - 10 |
| Sekundarstufe II     | Sekundarbereich II | 3   |  Sekundarstufe II | 11 - 13 | 
| Hochschule     | Hochschule | 9 |  Tertiärstufe  | |
| Hochschule  | Hochschule > Bachelor | 6|  Tertiärstufe  |  |
| Hochschule | Hochschule > Master |  7 | Tertiärstufe |  |
| Hochschule | Hochschule > Promotion |  8 | Tertiärstufe |  |
| Berufliche Bildung     |  Berufliche Bildung | **4?** |  Tertiärstufe   |  |
| Fortbildung     | Fortbildung | 9 |  |  |
| | | 9 | Weiterbildung |  | 
| | Vorbereitungsdienst|  9 |  | |
| Erwachsenenbildung     |  | 9 | |  |
| Förderschule     | | 9? |  | |
| || 9 | Sonderpädagogik |  | 
| Fernunterricht     | | 9 | Fernunterricht |  
| || 9 | Stufenunabhängig |  | 
| | | 9 | Nicht definiert | | 

Bzgl. "Hochschule":
Bachelor, Master lösen "Hochschule" als Stufen näher auf, stellen zugleich indirekt "Abschlüsse" und somit eine "Ausbildungsniveaustufe" dar. Hier würde sich ggf. anbieten "Bachelor" und "Master" dem Begriff "Hochschule" unterzuordnen?

**Beispiel: Feldbeschreibungen:**
[LOM-CH v2.1](https://www.educa.ch/sites/default/files/2020-11/applikationsprofil-lom-ch-v2.1-de.pdf): "Hauptsächliches Lernumfeld für die Verwendung der Ressource"

**ComeIn Lehr-/Lernkontexte** (educationalLevel): 
"Geben Sie an [...], in welchen ComeIn-relevanten Lehr-/Lehrkontexten bzw. zu welchem Zeitpunkt [...] (z. B. im Bachelor- und/oder Masterstudium usw.) die Ressource verwendet werden kann."
([AG Imedibi](https://www.uni-due.de/comein/ag-imedibi/), „Kernschema für die Beschreibung von ComeIn-relevanten Ressourcen. Hinweise zur Handhabung.“, CC BY 4.0.)

**schema.org**
"The level in terms of progression through an educational or training context." ~ Das Niveau/Die Stufe in Bezug auf das Fortschreiten in einem Bildungs- oder Ausbildungskontext. 

Querverweis:
[Zusammenhang: Vorgeschlagene Ergänzung educationalContext / educationalLevel in der Sitzung vom 12.10.21](https://pad.gwdg.de/2021-10-12-kim-oer?view#AMB-Profil-in-BIRD)

**Comment by acka47** [comment]
Der Vollständigkeit halber, hier noch eine weitere relevante Liste in diesem Kontext: die ISCED-2011 Level, siehe [hier](http://uis.unesco.org/sites/default/files/documents/international-standard-classification-of-education-isced-2011-en.pdf), Section 7, (S.21f). Ich blicke da aber auf die Schnelle nicht durch die Kodierung durch...

**Comment by oellers** [comment]
> Der Vollständigkeit halber, hier noch eine weitere relevante Liste in diesem Kontext: die ISCED-2011 Level, siehe [hier](http://uis.unesco.org/sites/default/files/documents/international-standard-classification-of-education-isced-2011-en.pdf), Section 7, (S.21f). Ich blicke da aber auf die Schnelle nicht durch die Kodierung durch...

Die Kodierung müsste die Zahl sein, d.h. "Primary education" ist das label und "1" wäre die Kodierung. Ich habe die Tabelle obig um das (vermutliche) Mapping ergänzt.

**Comment by acka47** [comment]
Es gibt halt auch Kodierung mit zwei und drei Stellen, darauf bezogen sich meine Verständnisprobleme. Beim BMBF gibt es aber eine sehr gute Übersicht, die Klarheit schafft: https://www.datenportal.bmbf.de/portal/de/G294.html

**Comment by oellers** [comment]
> Es gibt halt auch Kodierungen mit zwei und drei Stellen, darauf bezogen sich meine Verständnisprobleme. Beim BMBF gibt es aber eine sehr gute Übersicht, die Klarheit schafft: https://www.datenportal.bmbf.de/portal/de/G294.html

Je nach Präzision (Angabe von Kategorie und Unterkategorie) gibt es m.E. alle drei Ebenen, also einstellig bis dreistellige Kodierungen, da Kategorien nur "if applicable" (S.21), somit: 
**Level [+ Kategorie] [+ Subkategorie]**

Verwirrend ist jedoch in den Listen ggf., dass nicht alle möglichen Kombinationen aufgeführt sind, z. B. wird dort zwar die Kodierung "100" aufgeführt (obwohl durch eine solche Kodierung keinerlei Präzision zum Level 1 hinzugefügt wird), die Kodierung "200" wird jedoch nicht aufgeführt (obwohl diese eigentlich gültig sein müsste). Daher ist unklar, ob hier lediglich eine "2" oder eine "200" kodiert würde, wenn keine präzisieren Informationen vorliegen.

Beispiel:
- Über eine Ressource ist das Level 2 bekannt, jedoch nicht die Kategorien 4 und die Subkategorie 4. Wird hier nun einstellig nur die "2" kodiert oder würde "200" kodiert, um zu explizieren, dass es nicht näher definiert ist? 

Daher sind die Kodierungen in den Listen m.E. exemplarisch für konkrete (reale) Zuordnungen. Diesen Grad der Präzision erfassen wir jedoch vermutlich (derzeitig) nicht (sinnvoll), so dass wir auf dem ersten "Level" blieben, z. B. wissen wir in der Regel "0", jedoch nicht, ob dieses ein "010" oder "020" wäre. 

Dazu passt diese Passage:
"Not all combinations of categories and sub-categories exist or are widespread. Full listings of
these codes are given in Annexes II and III. If users of ISCED identify additional combinations of
categories and sub-categories, the list of three-digit codes can be expanded using the existing
codes reserved for additional dimensions." (S.22)

**Comment by sroertgen** [comment]
Moin @acka47,

du hast die ISCED Liste ja sogar schonmal in RDF modelliert: https://github.com/hbz/vocabs-edu/blob/master/isced-2013.ttl :)

**Comment by sroertgen** [comment]
Und hier eine die zu den Bildungsstufen passt: https://github.com/hbz/vocabs-edu/blob/master/isced-1997.ttl

**Comment by acka47** [comment]
> Und hier eine die zu den Bildungsstufen passt: https://github.com/hbz/vocabs-edu/blob/master/isced-1997.ttl

Die ISCED-2011 hatte ich aber nicht abgedeckt, warum auch immer...

**Comment by oellers** [comment]
Status: angenommen basierend auf Feedback der Mailingliste, im PR #143 und den Rückmeldungen in der [OER-Metadatengruppe vom 12.04.22](https://pad.gwdg.de/s/2022-04-12-kim-oer#educationalLevel) sowie der [Curricula-Gruppe vom 26.04.22](https://pad.gwdg.de/s/6wCbkSOtv#educationalLevel)

- [Werteliste zum Zeitpunkt der Annahme](https://github.com/dini-ag-kim/educationalLevel/tree/17a385cd8df24a52c644a28449283356acbeeb3c)
- [Beschreibung des zugehörigen Feldes zum Zeitpunkt der Annahme (HTML-Spezifikation)](https://github.com/dini-ag-kim/amb/blob/8f4bde874e10a553cf0e0145859b8ab2aba68824/draft/index.html#L838)

Follow up:
- Mapping der Werteliste auf ISCED-2011 und [OEH:educationalContext](https://github.com/openeduhub/oeh-metadata-vocabs/blob/master/educationalContext.ttl)
