### ISSUE TITLE
Ergänzung von `teaches`, `assesses` und `competencyRequired`

### ISSUE THREAD

**Issue by sroertgen** [dini-ag-kim/amb#108]
Im Zuge formalisierter Bildung werden meist Kompetenzframeworks eingesetzt, die beschreiben, was zu lernen ist, bzw. welche Kompetenz erworben werden soll.

Bei der Beschreibung von Lernressourcen kann es daher durchaus sein, dass diese auch mit entsprechenden Frameworks verknüpft werden. schema.org bietet dafür folgende Attribute an:

- [teaches](https://schema.org/teaches): Die beschriebene Ressource hilft eine Kompetenz oder ein Lernergebnis zu erreichen.
- [assesses](https://schema.org/assesses): Die beschriebene Ressource stellt eine Kompetenz oder ein Lernergebnis fest.
- [competencyRequired](https://schema.org/competencyRequired): Kenntnisse, Fähigkeiten oder persönliche Eigenschaften, die nachgewiesen werden müssen, um die Lernressource zu verstehen

Die [Kompetenzen in der digitalen Welt](http://w3id.org/kim/kmk-vocabs/digitalisierungsbezogene-kompetenzen/), die wir bereits abgebildet haben, könnten beispielsweise unter diesen Attributen verlinkt werden.
(Nachdem noch mehr Länder überzeugt werden, ihre Lehrpläne endlich maschinenlesbar bereit zu stellen, hoffentlich noch mehr...)

**Comment by sroertgen** [comment]
von Sodis gibt es einen API-Endpunkt über den ein Mapping der KMK-Kompetenzen in der digitalen Welt auf die Adaptionen von NRW und RLP gemappt werden: https://cp.sodis.de/api/get/?kmk_digital_competency=*

**Comment by oellers** [comment]
> von Sodis gibt es einen API-Endpunkt über den ein Mapping der KMK-Kompetenzen in der digitalen Welt auf die Adaptionen von NRW und RLP gemappt werden: https://cp.sodis.de/api/get/?kmk_digital_competency=*

Die IDs der Kompetenzen von SODIS wurden für den Medienkompetenzrahmen als Grundlage verwendet, so dass ein Mapping recht leicht übertragbar ist. Ein Mapping in den o.g. SKOS derzeitig ist noch nicht abgebildet, jedoch angedacht.

**Comment by acka47** [comment]
Wir haben uns im heutigen Treffen darauf geeinigt, dass AMB in diesem Fall nicht normativ die zu nutzenden kontrollierten Vokabulare vorgeben soll, sondern allenfalls Beispiele nennen soll. Das Schema könnte dementsprechend einfach nur vorgeben, dass die verlinkten Kompetenzen zumindest einen URI als Identifier haben. Das sähe dann am Beispiel von `teaches` etwa so aus:

```json
{
    "$id": "https://w3id.org/kim/amb/draft/schemas/teaches.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Teaches",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uri",
        },
        "prefLabel": {
          "title": "The preferred label of the concept",
          "description": "A localized string for prefLabel of a SKOS concept",
          "$ref": "https://w3id.org/kim/amb/draft/schemas/LocalizedString.json"
        }
      },
      "required": [
        "id"
      ]
    }
  }
```
