### ISSUE TITLE
Vor- und Nachnamen als separate Felder für JSON-Objekte vom Typ "Person"

### ISSUE THREAD

**Issue by zazi** [dini-ag-kim/amb#109]
Für eine bessere/ genauere Formatierung der Personennamen wären separate Felder für den Vor- und Nachnamen hilfreich. Dies könnte z.B. eine bessere Sortierung aber auch Auffindbarkeit ermöglichen. Die entsprechenden Felder [familyName](https://schema.org/familyName) für den Nachnamen und [givenName](https://schema.org/givenName) für den/ die Vornamen sind bereits in den Feldern für den schema.org-Typen [Person](https://schema.org/Person) enthalten (zusätzlich auch das Feld [additionalName](https://schema.org/additionalName) für mögliche "Mittelnamen"). Es wäre wünschenswert, wenn diese Felder optional, d.h., je nach Lage der Quelldaten bzw. Eingabemasken, mit erfasst werden könnten.
Ob sich das Ganze jetzt auch gut mit den Mitteln von JSON-Schema abbilden lässt kann ich im Moment auch nicht sagen. Da dies ja, wenn dann, immer nur für "creator" oder "contributor" vom Typ "Person" zutreffen würde und nicht vom Typ "Organization".

**Comment by acka47** [comment]
Danke für die Anfrage. Ich hatte mich in https://github.com/dini-ag-kim/lrmi-profile/issues/85#issue-926146814 – mit Verweise auf https://www.w3.org/International/questions/qa-personal-names – für die simple Version des vollständigen Namens ausgesprochen  und müsste immer noch überzeugt werden. warum eine Strukturierung der Namen perspektivisch mehr Nutzen als Probleme mit sich brächte.

**Comment by jnauber** [comment]
Für die Nachnutzung von LRMI-Metadaten (zum Beispiel aus oersi.de) in Anwendungen, wie Discovery Systemen, wäre es gut, wenn es im DINI AG KIM LRMI-Profil die Möglichkeit gäbe Vor-. Mittel- und Nachnamen (evtl. Titel/Anrede) getrennt von einander auszuweisen. Jedes nachnutzende System könnte so eine andere Form der Darstellung von Personennamen wählen. Folgendes Beispiel verdeutlicht dies:

- oersi.de = Vorname Nachname
- SLUB Katalog = Nachname, Vorname

**Comment by kulla** [comment]
Zur Ergänzung: Bei serlo.org speichern wir nur einen Benutzernamen, welcher auch pseudonomysiert sein kann. In meinem Serlo-Profil ist es beispielsweise mein Benutzername [`Kulla`](https://de.serlo.org/user/26217/kulla). Dementsprechend könnten wir `familyName` und `givenName` bei den Autor:innendaten nicht mitliefern.  Ich gehe aber richtig der Annahme, dass in diesem Vorschlag `givenName` und `familyName` neben dem aktuell schon bestehenden `name` Paramater als optionale Parameter aufgenommen werden sollen, richtig?

**Comment by acka47** [comment]
> Ich gehe aber richtig der Annahme, dass in diesem Vorschlag `givenName` und `familyName` neben dem aktuell schon bestehenden `name` Paramater als optionale Parameter aufgenommen werden sollen, richtig?

Wenn wir das ergänzen würden, dann als optionale Ergänzung, ja. Im letzten Treffen haben wir allerdings beschlossen, das erstmal ganz zu lassen. Stattdessen wird @jnauber bei OERSI ein entsprechendes Ticket anlegen, dass wir dort die Daten srukturiert liefern mit `givenName` und `familyName`, wenn die Quelldaten das hergeben. Siehe die Notizen unter https://pad.gwdg.de/s/2022-01-11-kim-oer#Abbildung-von-Personennamen.

Von daher schließe ich das Ticket auch erstmal wieder.
