### ISSUE TITLE
Erlaube DateTime in Datumsfeldern

### ISSUE THREAD

**Issue by kulla** [dini-ag-kim/amb#117]
Mir ist aufgefallen, dass in den Beispielen nur Datumsangaben der Form `YYYY-MM-DD` vorkommen. Gehe ich richtig der Annahme, dass bei Datumsangaben zu Attributen wie [`dateCreated`](https://dini-ag-kim.github.io/amb/draft/#datecreated) sowohl [Date](https://schema.org/Date) als auch [DateTime](https://schema.org/DateTime) Werte angegeben werden können (so wie bei https://schema.org/dateCreated)? Wenn ja, könnte man unter https://dini-ag-kim.github.io/amb/draft/#datecreated beim Feld `Typ` neben `Date` auch den Typen `DateTime` aufnehmen...

PS: Ich beschäftige mich erst seit relativ kurzer Zeit mit JSON-LD und dem AMB Standard. Danke an dieser Stelle für die gute Doku! :heart:  Dementsprechend haben sich bei mir aber einige Fragen ergeben, die ich nun in Issues stelle (hoffe das passt). Gegebenenfalls ist es sinnvoll, hierfür das [discussions-feature](https://docs.github.com/en/discussions) in diesem Repo zu aktivieren. So gibt es einen zentralen Ort, um Fragen rund um AMB zu sammeln und zu beantworten.

**Comment by acka47** [comment]
Hallo @kulla, danke für dieses Ticket und die anderen. Du stellst da sehr gute Fragen, ich werde dir allerdings voraussichtlich erst Mitte Januar antworten können, weil ich zur Zeit Urlaub habe.

**Comment by acka47** [comment]
So, jetzt habe ich Zeit für eine adäquate Antwort. Prinzipiell spricht ja nichts gegen mehr Genauigkeit, von daher könnten wir das aus meiner Sicht gerne umsetzen. (In https://github.com/dini-ag-kim/amb/pull/97 hatte ich mich auch dafür ausgesprochen, weniger Genauigkeit zu erlauben. Da konnten wir uns aber nicht drauf einigen, weshalb es erstmal bei `Date` geblieben ist.)

Ich habe den Namen de sTickets angepasst und den Pull Request #120 aufgemacht, der die nötigen Änderungen an Schema, Beispielen und Spec implementiert. Wir können das ja gleich beim Treffen mal diskutieren und schauen ob es Einwände gibt.

**Comment by kulla** [comment]
Dank dir. Ich habe noch https://github.com/dini-ag-kim/amb/pull/121 als Änderungsvorschlag hinzugefügt.

> Wir können das ja gleich beim Treffen mal diskutieren und schauen ob es Einwände gibt.

Wann findet das nächste Treffen statt? Ich wäre gerne mit dabei.
