### ISSUE TITLE
Werden die Metadaten als JSON oder JSON-LD gelesen?

### ISSUE THREAD

**Issue by kulla** [dini-ag-kim/amb#118]
Nach meinen Verständnis gibt es in JSON-LD untereinander äquivalente Formen, die als JSON gesehen verschieden sind. So ist die Angabe der Lizenz als String

```json
{
  "license": "https://creativecommons.org/licenses/by-sa/4.0/deed.de"
}
```

im Ergebnis dasselbe wie die Angabe als Objekt mit einem `id`-Attribut (auf AMB mit dem Context `id === @id` bezogen):

```json
{
  "license": {
    "id": "https://creativecommons.org/licenses/by-sa/4.0/deed.de"
  }
}
```

Sind im Sinne von AMB beide Darstellungen erlaubt? Sprich: Wird davon ausgegangen, dass die Metadaten als JSON-LD gelesen werden, welches die unterschiedlichen Darstellungen anpasst. Oder ist der Sinn vielmehr, dass Crawler die Metadaten als JSON einlesen können und die URL von Lizenzen stets unter `metadata.license.id` gefunden werden kann?

Ich persönlich sehe Vorteile in beiden Richtungen. Wenn die Metadaten als JSON-LD geparst werden, erlaubt dies Freiheiten in der Darstellung. So sind kürzere Darstellungen wie `"inLanguage": "de"` und Spezialfälle wie Doppellizenzen möglich (bspw ist https://www.youtube.com/watch?v=dxqc2sWgiz8  doppellizenziert unter CC-BY-SA und Youtube-Lizenz). Auf der anderen Seite erleichtert es Crawler die Arbeit, wenn das JSON immer dieselbe Struktur hat.

**Comment by acka47** [comment]
> Sind im Sinne von AMB beide Darstellungen erlaubt? 

Nein.

> Sprich: Wird davon ausgegangen, dass die Metadaten als JSON-LD gelesen werden, welches die unterschiedlichen Darstellungen anpasst. 

Die Daten werden als JSON gelesen mit dem Bonus, dass sie gleichzeitig JSON-LD und damit RDF sind. Die Menschen, die das Profil implementieren, müssen aber nur Ahnung von JSON haben, nicht von RDF. Wenn wir verschiedene JSON-LD-Repräsentationen oder gar andere RDF-Serialisierungen erlauben würden, hätten wir eine andere Validierungsmethode als JSON Schema wählen müssen, z.B. [ShEx](https://shex.io/) oder [Shacl](https://www.w3.org/TR/shacl/). Für die Linked-Data-Nerds wäre das ok. Da aber viel mehr Leute Verständnis von JSON als von RDF haben, haben wir JSON als Format und JSON Schema als Validierungsmethode gewählt und das Ganze durch Ergänzung eines Kontexts aber Linked-Data-kompatibel gemacht.

> Oder ist der Sinn vielmehr, dass Crawler die Metadaten als JSON einlesen können und die URL von Lizenzen stets unter `metadata.license.id` gefunden werden kann?

Hier stellt sich die Frage, was überhaupt der Sinn des Profils ist. Einen Crawler entwickeln und pflegen wir ja von hbz und TIB: den für [OERSI](https://oersi.de). Da gehen wir gar nicht von aus, dass wir irgendwann die Daten einfach nur noch einsammeln und indexieren können. Wir wissen, dass wir bei den meisten Quellen immer einen Transformationsschritt dazwischenschalten müssen. Wichtig ist da vor allem, dass gemeinsame kontrollierte Vokabulare benutzt werden wie HCRT oder die Hochschulfächersystematik. Ob das `license`-Feld ein Objekt oder einen String als Wert hat, ist uns relativ egal, dass können wir leicht anpassen. Für mich ist der Sinn des Profils eher, dass es als Orientierung dient für alle, die sich Gedanken über die Metadaten zu ihren Bildungsressourcen machen. Diesen gibt es klare Vorgaben, wie gute Metadaten aussehen können.

Zum konkreten Punkt, warum wir hier ein Objekt verlangen: Anwendungen wie OERSI wollen ja in einer Detailansicht nicht die Lizenz-URL anzeigen, sondern einen menschenlesbaren String. Deshalb ist es prinzipiell sinnvoll, bei Knoten, die durch einen URI identifiziert werden, immer ein Objekt zu benutzen, auch wenn erstmal nur die URI geliefert wird. So kann später immer noch der Anzeige-String mit `name`, `label` o.ä. ergänzt werden, ohne dabei die bisherige Datenstruktur zu verändern und existierende Anwendungen kaputt zu machen. Deshalb sieht es beim `learningResourceType`-Feld ähnlich aus, wo wir auch nur eine `id` als Pflichtfeld haben, dennoch aber einen Array mit Objekten verlangen, siehe https://w3id.org/kim/amb/draft/#learningresourcetype. (Vieler dieser Rückwärtskompatibilitätsgedanken müsste mensch sich natürlich nicht machen, wenn wir auf RDF-Basis operieren würden, aber das hat sich leider bisher nicht in den Mainstream durchgesetzt...)

**Comment by kulla** [comment]
@acka47 Finde diese Entscheidung gut. :+1: Ich denke, dass die Spezifikation diese Entscheidung explizit widerspiegeln sollte und habe deswegen https://github.com/dini-ag-kim/amb/pull/128 als Vorschlag erstellt (bin aber noch nicht 100% zufrieden mit der Formulierung).

Aus meiner Sicht sollten Konsumenten sich dann verlassen können, dass die JSON-Struktur bei Metadaten, die diesen Standard erfüllen, stets gleich ist. Deswegen ist der Fall der Doppellizenz für mich noch eine offene Frage, für die ich aber separat ein Issue erstelle.
