### ISSUE TITLE
AMB wird von validator.schema.org nicht erkannt

### ISSUE THREAD

**Issue by kulla** [dini-ag-kim/amb#119]
Es scheint so zu sein, dass `https://w3id.org/kim/lrmi-profile/draft/context.jsonld` von https://validator.schema.org/ nicht erkannt wird. Wenn ich dort einen Test mit folgenden JSON-LD laufen lasse:

```json
{
  "@context": [
    "https://w3id.org/kim/lrmi-profile/draft/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "id": "https://serlo.org/1495",
  "type": [
    "LearningResource",
    "Article"
  ],
  "dateCreated": "2014-03-01T20:36:44+00:00",
  "dateModified": "2021-03-08T20:51:17+00:00"
}
```

so erhalte ich den Fehler "Das JSON-LD-Dokument enthält einen ungültigen Typ." (Auch `@type` wird nicht richtig erkannt):

![2021-12-18-231139_475x413_scrot](https://user-images.githubusercontent.com/1327215/146656835-34654879-b904-496e-a51c-48fa8c8a4565.png)

Der Fehler verschwindet, wenn ich die Definition von https://w3id.org/kim/lrmi-profile/draft/context.jsonld in `@context` direkt einbaue:

```json
{
  "@context": [
    {
      "@vocab": "http://schema.org/",
      "type": "@type",
      "id": "@id",
      "@language": "de"
    }
  ],
  "id": "https://serlo.org/1495",
  "type": [
    "LearningResource",
    "Article"
  ],
  "dateCreated": "2014-03-01T20:36:44+00:00",
  "dateModified": "2021-03-08T20:51:17+00:00"
}
```

Ergebnis:

![2021-12-18-231234_472x283_scrot](https://user-images.githubusercontent.com/1327215/146656859-05a02134-781a-4244-8901-7a258adb342f.png)

Gegebenenfalls liegt der Bug auch in validator.schema.org, wo externe `@context` Definitionen nicht richtig auflöst werden. Es wäre gut, wenn das JSON-LD von AMB auch von Google und Co richtig erkannt wird. Ein Workaround wäre es natürlich die Definition von https://w3id.org/kim/lrmi-profile/draft/context.jsonld direkt `@context`, was aber sicherlich keine Lösung ist.

**Comment by acka47** [comment]
> Gegebenenfalls liegt der Bug auch in validator.schema.org, wo externe @context Definitionen nicht richtig auflöst werden.

Ja, so sehe ich das. ;-) Google erwartet derzeit die Referenz zu schema.org direkt im JSON-Dokument, nicht vermittelt über einen externen JSON-LD-Kontext.

> Es wäre gut, wenn das JSON-LD von AMB auch von Google und Co richtig erkannt wird.

Das kann ich verstehen. Für mich persönlich ist das über die Jahre ehrlich gesagt immer unwichtiger geworden, weil mir Anwendungsbeispiele fehlen, wo Google wirklich etwas mit diesen `CreativeWork`-Metadaten macht. Ich habe bisher weder Rich Snippets von OER in Ergebnislisten gesehen noch davon gehört, dass schema.org-Markup die Indexierungswahrscheinlichkeit erhöht.

Wir können gerne überlegen, wie wir deinem Wunsch gerecht werden. Eine Möglichkeit wäre es, in der Spec beide Möglichkeiten zu erlauben:

1. Referenzierung des externen JSON-LD-Kontexts
2. Einbettung des Kontexts im JSON-LD (was wir zwischendurch auch mal hatten, siehe https://github.com/dini-ag-kim/amb/commit/e0bfbaae9211a782b8e674affe1ec14e32ce5453, allerdings ist die Referenzierung eines externen Kontexts einfach nutzerfreundlicher...)

Ein zweite Möglichkeit, wäre es zwei externe Kontexte anzugeben: schema.org und die Ergänzungen für AMB:

```json
  "@context": [
    "https://schema.org",
    "https://w3id.org/kim/amb/draft/context.jsonld",
    {
      "@language": "de"
    }
  ]
```

**Comment by kulla** [comment]
> Ja, so sehe ich das. ;-) Google erwartet derzeit die Referenz zu schema.org direkt im JSON-Dokument, nicht vermittelt über einen externen JSON-LD-Kontext.

Okay, ich habe entsprechend ein Issue dafür im schemaorg repo angelegt: https://github.com/schemaorg/schemaorg/issues/3036
 
> Das kann ich verstehen. Für mich persönlich ist das über die Jahre ehrlich gesagt immer unwichtiger geworden, weil mir Anwendungsbeispiele fehlen, wo Google wirklich etwas mit diesen `CreativeWork`-Metadaten macht. Ich habe bisher weder Rich Snippets von OER in Ergebnislisten gesehen noch davon gehört, dass schema.org-Markup die Indexierungschancen erhöht.

Ja, das ist sicherlich von Projekt zu Projekt unterschiedlich. Für uns ist auf jeden Fall relevant. Der Post https://github.com/schemaorg/schemaorg/issues/2921#issuecomment-879817283 zeigt zumindest, dass validator.schema.org die Art und Weise widerspiegelt, wie Google auf die Metadaten schaut. (Quote: "[SMV] it is a view provided by Google's structured data validation infrastructure")
 
> Wir können gerne überlegen, wie wir deinem Wunsch gerecht werden. Eine Möglichkeit wäre es, in der Spec beide Möglichkeiten zu erlauben

Perfekt. Ich denke genau das ist die Lösung. Eine Alternative ist im Übrigen auch:

```json
{
  "@context": [
    "https://w3id.org/kim/lrmi-profile/draft/context.jsonld",
    {
      "@language": "de",
      "@vocab": "http://schema.org/",
      "type": "@type",
      "id": "@id"
    }
  ],
}
```

Ich glaube, dass AMB keine genaue Spezifikation für die Angabe von `@context` braucht (Zumindest nicht, dass hier das JSON genau spezifiziert wird). Hauptsache, es wird irgendwie auf https://w3id.org/kim/lrmi-profile/draft/context.jsonld verwiesen. Daneben sollte es die Möglichkeit geben, weitere Spezifikationen im Sinne von JSON-LD aufzunehmen und Datenfelder zu beschreiben, die nicht in AMB spezifiziert sind. Deine und mein Workaround sollte also durch AMB erlaubt sein. Bist du derselben Meinung?
