### ISSUE TITLE
honorificPrefix

### ISSUE THREAD

**Issue by TobiasNx** [dini-ag-kim/amb#122]
Um Angaben zum akademischen Grad bei `creator` und `contributor` einzubinden.
Schlage ich vor https://schema.org/honorificPrefix als Feld in `creator` und `contributor` einzubinden.

Manche Projekte z.B. ORCA sind auf diese Angaben angewiesen.

**Comment by kulla** [comment]
Verständnisfrage: Dieses Attribut soll als optionaler Parameter hinzugefügt werden, oder? Bei serlo.org führen wir dieses Attribut bei den Autor:innendaten nicht (siehe https://github.com/dini-ag-kim/amb/issues/109#issuecomment-1016715444 ) und können es so auch nicht exportieren.

**Comment by acka47** [comment]
> Dieses Attribut soll als optionaler Parameter hinzugefügt werden, oder?

Ja, es hat ja eh nicht jede Person einen Titel.

**Comment by kulla** [comment]
> Ja, es hat ja eh nicht jede Person einen Titel.

Passt :+1: Finde diesen Vorschlag super. Eine eher technische Frage habe ich noch. Nehmen wir den Fall eines CC-BY Lehrmaterials mit einem `creator`:

```json
{
  "name": "Anna Müller",
  "honorificPrefix": "Dr."
}
```

Wenn ich dieses Material verwende, muss ich diese Autorin nennen. Zeige ich nun `Dr. Anna Müller` oder `Anna Müller` an? Dies ist insbesondere dadurch relevant, als dass bei CC-BY die Autor:innen selbst bestimmen können, wie ihr Name dargestellt wird.

Und noch eine andere Sache, die mir bei diesem Beispiel auffällt. Gehört der Punkt eigentlich zu `honorificPrefix` oder nicht? Habe ich

```json
{
  "name": "Anna Müller",
  "honorificPrefix": "Dr."
}
```

oder doch

```json
{
  "name": "Anna Müller",
  "honorificPrefix": "Dr"
}
```

**Comment by TobiasNx** [comment]
@kulla: ich kann deinen Beitrag nicht zitieren. Daher so.

1.
Es scheint in den Attributierungsregeln bei Creative Commons keine Regel zu existieren, ob man Titel verwenden kann oder nicht. Ich würde behaupten, die gehören nicht zur Attributierung. Autor:innen werden auch bei Artikeln oder Büchern vorne nicht inkl. ihrer akademischer Titel angegeben.

2.
Ich würde mich an dieser Stelle gegen ein kontrolliertes Vokabular aussprechen, da akademische Titel enorm variable ist und sich im englisch-sprachigen Kontext auch vom deutschen Kontext unterscheidet.

**Comment by kulla** [comment]
> Es scheint in den Attributierungsregeln bei Creative Commons keine Regel zu existieren, ob man Titel verwenden kann oder nicht.

In der CC-BY 4.0 lautet der Text (siehe [3.a.1.A.i](https://creativecommons.org/licenses/by/4.0/legalcode): "If You Share the Licensed Material (including in modified form), You must retain the [...] identification of the creator(s) of the Licensed Material and any others designated to receive attribution, in any reasonable manner requested by the Licensor (including by pseudonym if designated)" Ich lese es so, dass wenn eine Person bei der Namensnennung die Angabe des Doktortitels wünscht, diesem Wunsch nachkommen werden soll und analog, wenn dies nicht gewünscht ist.

In meiner praktischen Erfahrung mit OER ist dies sicherlich eher ein Randthema. Es bleibt aber die Frage: Wie weiß ich als Konsument, in welcher Form der Autor / die Autorin die Namensnennung wünscht?

**Comment by kulla** [comment]
> Ich würde mich an dieser Stelle gegen ein kontrolliertes Vokabular aussprechen, da akademische Titel enorm variable sind und sich im englisch-sprachigen Kontext auch vom deutschen Kontext unterscheiden.

Passt für mich. :+1:
