### ISSUE TITLE
Publisher um Type "Person" erweitern

### ISSUE THREAD

**Issue by mirjan-hoffmann** [dini-ag-kim/amb#136]
Es gibt immer mal wieder Materialien, die keine Organisation als Herausgeber haben, sondern natürliche Personen.

Beispiel https://av.tib.eu/media/9474

Daher sollte als `type` beim Publisher zusätzlich `Person` möglich sein.

**Comment by TobiasNx** [comment]
Die Funktion "Herausgeber" passt nicht zum Feld "publisher".
Das sollte eher eine Rollenzuweisung bei "contributor" sein. Hier wäre zu überlegen, welche Rollenfunktion man angibt und wie.

Eine Möglichkeit wäre marcRelatoren zu nutzen. Die sind verbreitet.

**Comment by TobiasNx** [comment]
(Das könnte an sich auch ein Problem des labelings auf Seiten von TIB AV sein.)

**Comment by mirjan-hoffmann** [comment]
Das sehe ich aber nicht als praktikabel an. Du spielt vermutich darauf an, dass "publisher" als "Verlag" übersetzt wird und "Verlag" != "Herausgeber", oder? Ebenso wird aber durch jeden von mir getesteten Übersetzer "publisher" als "Herausgeber" übersetzt - vermutlich, da beides so nah beieinander liegt. Es kommt also ganz auf die Definition der Übersetzung ins Deutsche an was hier aufgeführt wird. In der Praxis kann man daher davon ausgehen, dass sowohl "Verlage" als auch "Herausgeber" im Feld "publisher" aufgeführt sein werden.

**Comment by TobiasNx** [comment]
Es sind schon semantische Unterschiede, oder:
Herausgeber:innen bei Buchpublikationen, Zeitschriften, etc. haben andere Funktion als Verlage, zumal es sowohl Herausgeber:innen als auch Verlage/Verlegende Einrichtungen für eine Publikation/Ressource geben kann.:

Von marc rel: https://www.loc.gov/marc/relators/relaterm.html

 Editor [edt]
    A person, family, or organization contributing to a resource by revising or elucidating the content, e.g., adding an introduction, notes, or other critical matter. An editor may also prepare a resource for production, publication, or distribution. For major revisions, adaptations, etc., that substantially change the nature and content of the original work, resulting in a new work, see author  (auch: https://schema.org/editor))

 Issuing body [isb]
    A person, family or organization issuing a work, such as an official organ of the body

 Publisher [pbl]
    A person or organization responsible for publishing, releasing, or issuing a resource

**Comment by mirjan-hoffmann** [comment]
> Es sind schon semantische Unterschiede

Das bestreite ich auch nicht. Ich denke nur, dass es auf Grund der gängigen Übersetzungen `publisher-Verlag` und `publisher-Herausgeber` schwer wird diese Unterscheidung mit einem Feld `publisher` sicher in der Praxis durchzusetzen.

Wie dem auch sei, da in Deiner Beschreibung/Definition bei "Publisher" (Verlag) auch Personen aufgelistet sind, passt doch die Erweiterung dieses Issues trotzdem, auch wenn ich in der Issue-Beschreibung oben "Herausgeber" durch "Verlag" ersetzen würde.

**Comment by TobiasNx** [comment]
Hatte auch meine Zustimmung zum MR gegeben, ich denke aber, dass man `role` bei Creator, Contributor ergänzen könnte. ;)

**Comment by acka47** [comment]
> Hatte auch meine Zustimmung zum MR gegeben, ich denke aber, dass man role bei Creator, Contributor ergänzen könnte. ;)

Siehe dazu meinen Kommentar unter https://github.com/dini-ag-kim/amb/pull/137#issuecomment-1042763692:

> MARC Relator Codes würden die Möglichkeiten zur Rollenbeschreibung drastisch erhöhen. Allerdings wäre die Änderung nicht rückwärtskompatibel – wenn wir es nicht als zusätzliche Möglichkeit einführen – und würde die Komplexität und leichte Verständlichkeit und Anwendbarkeit des Datenmodells – durch die Einführung eines weiteren ["level of indirection"](https://en.wikipedia.org/wiki/Fundamental_theorem_of_software_engineering) – erhöhen. Wir könnten dazu zwar schema.org's [`Role`](https://schema.org/Role) type ([Blogpost](http://blog.schema.org/2014/06/introducing-role.html)) verwenden. Soweit ich das mitbekommen habe, wird das aber bisher in der Praxis kaum verwendet.
>
> Ich denke, wir sollten mit einer Umsetzung warten, bis sich tatsächlich mehr als ein Projekt meldet, das entsprechende Informationen über (O)ER unter Nutzung des AMB enkodieren möchte.
