### ISSUE TITLE
Registrierung von IANA Media Type application/vnd.h5p+zip

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/amb#146]
Entstanden aus https://github.com/dini-ag-kim/hcrt/issues/14

Wahrscheinlich ist der Media Type im "vendor tree" zu registrieren: `application/vnd.h5p+zip`

Das Registrierungsformular ist hier: https://www.iana.org/form/media-types Darin sind auch die relevanten RFCs verlinkt.

@otacke hat [via Twitter](https://twitter.com/otacke/status/1511266767074639876) angeboten, uns bei konkreten Fragen zu helfen.

**Comment by oellers** [comment]
Da es auf die [Anfrage im Forum](https://h5p.org/node/1249245) keine Reaktion gab, ggf. nochmal im [h5p community chat](https://gitter.im/h5p/CommunityChat)?

Bzgl. tree käme vllt. auch ein Subtyp-[Suffix](https://en.wikipedia.org/wiki/Media_type#Suffix) in Betracht.
application/zip+h5p (oder umgekehrt +zip, falls eigener subtyp)

**Comment by otacke** [comment]
@oellers Gitter wird schon lange nicht mehr (vom H5P Kernteam) genutzt und dürfte auch sonst ein Exot sein.

**Comment by acka47** [comment]
Ich meine, der letzte Stand war hier, dass wir das einfach innerhalb KIMs angehen können. @otacke hatte m.E. zugesagt, dass wir ihn dann als Ansprechpartner für den IANA Type angeben können, richtig?

**Comment by otacke** [comment]
@otacke hat zugesagt, dass er bei konkreten, H5P bezogene Fragen nach besten Kräften hilft. Mit der Registrierung habe ich keine Erfahrung.

**Comment by acka47** [comment]
> Mit der Registrierung habe ich keine Erfahrung.

Ja, das meinte ich auch nicht. Ich meinte mich zu erinnern, dass wir auch schon die Frage angesprochen hatten, worauf wir unter "Reference" in der [IANA Liste](https://www.iana.org/assignments/media-types/media-types.xhtml) verweisen und deinen E-Mail-Kontakt als Option im Raum Stand. Am besten tragen wir da wahrscheinlich aber eh einen Link auf die OER-Metadatengruppe  ein oder so, da eine persönliche Mail-Adresse vermutlich nicht so zukunftssicher ist.

**Comment by acka47** [comment]
Wir werden das in dieser Gruppe nicht umsetzen, weshalb das Ticket geschlossen wird.
