### ISSUE TITLE
Erlaube Angabe einer Trailer-URL mit sdo:trailer 

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/amb#155]
Im ORCA-Kontext ist angedacht für komplexere OER – z.B. einen Kurs – einen Trailer zu erstellen, der einen schnellen Einblick in Charakter und Inhalt der Ressource gibt. Für das Entdecken von OER ist es sicher hilfreich, möglichst früh auf die Existenz eines solchen Trailers hingewiesen zu werden (in OERSI könnte ein Trailer etwa in die Detailanzeige einer Ressource eingebettet werden).

Vorschlag zu Ergänzung analog zu `encoding`:

> ### <dfn>trailer</dfn>
>
> Ein Trailer/Video-Teaser zu einer Ressource .
<blockquote>
<dl>
<dt>Pflichtfeld</dt>
<dd>nein</dd>
<dt>Typ</dt>
<dd><code>array[object]</code></dd>
<dt>Elemente</dt>
<dd>JSON-Objekt, das <code>"type": "VideoObject"</code> sowie die Property <code>contentUrl</code> oder <code>embedUrl</code> enthalten MUSS und folgende weitere Properties enthalten KANN: <code>contentSize</code> (in bytes ohne Maßangabe) , <code>embedUrl</code>, <code>sha256</code>, <code>bitrate</code> (in kb/s ohne Maßangabe) sowie <code>encodingFormat</code>, das bei Verwendung Werte aus [[IANA-MEDIA-TYPES]] enthalten MUSS.</a></dd>
<dt>Validierung</dt>
<dd><a href="https://w3id.org/kim/amb/draft/schemas/trailer.json">JSON Schema</a></dd>
</dl>
</blockquote>

JSON-Beispiel:

```json
{
   "id":"https://example.org/oer-course",
   "type":[
      "LearningResource",
      "Course"
   ],
   "name":"An example course",
   "trailer":[
      {
         "type":"VideoObject",
         "encodingFormat":"video/mp4",
         "contentSize":"9803150",
         "contentUrl":"https://example.org/trailer.mp4",
         "embedUrl":"https://embed.example.org/trailer.mp4"
      }
   ]
}
```

Diskutieren könnten wir noch, ob es ein Array sein sollte oder immer nur ein Trailer pro Ressource erwartet werden sollte.

**Comment by acka47** [comment]
Ich hätte gerne mindestens zwei Reviewer für diesen PR, der inhaltlich bereits im Treffen besprochen wurde. @sroertgen und @mirjan-hoffmann, wärt ihr dazu bereit?

**Comment by mirjan-hoffmann** [comment]
Mich würde noch interessieren (habe die Diskussion nicht mitbekommen): wie konkret sind denn tatsächliche Anwendungsfälle? "ist angedacht" könnte auch einfach eine "nette Idee" sein. Oder gibt es bereits tatsächlich Trailer? Kann mit gerade nicht so gut vorstellen, dass dies ausgiebig genutzt wird...

**Comment by acka47** [comment]
> Mich würde noch interessieren (habe die Diskussion nicht mitbekommen): wie konkret sind denn tatsächliche Anwendungsfälle? "ist angedacht" könnte auch einfach eine "nette Idee" sein

Wenn ich das richtig verstanden habe, wird die Erstellung eines Trailers verpflichtend sein, zumindest in manchen Förderlinien.

> Oder gibt es bereits tatsächlich Trailer? Kann mit gerade nicht so gut vorstellen, dass dies ausgiebig genutzt wird...

Ich bin bereits in der Vergangenheit häufiger auf Trailer gestoßen. Schaut man sich die [Kurse in OERSI](https://oersi.org/resources/?learningResourceType=%5B%22https%3A%2F%2Fw3id.org%2Fkim%2Fhcrt%2Fcourse%22%5D) an, findet man auch schnell welche, z.B.:

iMoox:
- https://imoox.at/course/maker
- https://imoox.at/course/lebenszyklus

HOOU:
- https://www.hoou.de/projects/biotechall/preview
- https://www.hoou.de/projects/mlea-advanced-topics-in-law-economics-third-semester/preview

TU Delft:
- https://ocw.tudelft.nl/courses/framing/

OnCampus:
- https://www.oncampus.de/Customer_Experience_Management

OpenVHB:
- https://open.vhb.org/blocks/ildmetaselect/detailpage.php?id=64
- https://open.vhb.org/blocks/ildmetaselect/detailpage.php?id=78
- https://open.vhb.org/blocks/ildmetaselect/detailpage.php?id=118
- https://open.vhb.org/blocks/ildmetaselect/detailpage.php?id=140
- https://open.vhb.org/blocks/ildmetaselect/detailpage.php?id=133

Open HPI:
- https://open.hpi.de/courses/bayesian-statistics2023
- https://open.hpi.de/courses/designthinkinginorganisations2020

Ich schaue mal jetzt nicht noch bei weiteren Quellen. Es sollte aber klar geworden sein, dass Trailer/Teaser/Videozusammenfassungen von Kursen bereits jetzt gängige Praxis sind und dass das keine ORCA-spezifische Sache ist.

**Comment by mirjan-hoffmann** [comment]
Super, vielen Dank für die ausführliche Erklärung!

**Comment by mirjan-hoffmann** [comment]
Bei der Implementierung im OERSI (https://gitlab.com/oersi/oersi-backend/-/issues/47) fiel auf, dass die Trailer-Property noch im https://github.com/dini-ag-kim/amb/blob/main/draft/schemas/schema.json fehlt

**Comment by acka47** [comment]
> Bei der Implementierung im OERSI (https://gitlab.com/oersi/oersi-backend/-/issues/47) fiel auf, dass die Trailer-Property noch im https://github.com/dini-ag-kim/amb/blob/main/draft/schemas/schema.json fehlt

Danke für den Hinweis, @mirjan-hoffmann . [d8f96d6](https://github.com/dini-ag-kim/amb/pull/165/commits/d8f96d62829920374134fd50d26841fcbb3794c7) sollte das fixen, siehe #165. Tatsächlich waren Beispiel und Schema auch widersprüchlich, das eine mit Array das andere ohne. Ich hab im Beispiel den Array entfernt,  da wir – wie bei `image`/Thumbnail hier nur einen repräsentativen Trailer pro Ressource erwarten. In den in https://github.com/dini-ag-kim/amb/issues/155#issuecomment-1247642083 genannten Beispielen findet sich auch nur jeweils ein Trailer, so dass das übereinstimmt.
