### ISSUE TITLE
Ergänzung von `sameAs`

### ISSUE THREAD

**Issue by sroertgen** [dini-ag-kim/amb#168]
Formulierung des use cases folgt.

**Comment by bokahama** [comment]
Die Notwendigkeit die (Inhalts-)Gleichheit oder wenigstens die **Identität von Bildungs-Ressourcen** in den Metadaten bzw. Datensätzen festzuhalten ergibt sich aus zumindest zwei praktischen Szenarien:
+ Verschiedene **Metadatenaggregatoren** (wie z.B. SODIX/MUNDO oder OpenEduHub/WLO) **harvesten zum Teil die gleichen Content-Quellen** und erzeugen dabei jeweils eigene (ähnliche) Datensätze, die auf den selben Inhalt und meist (aber nicht zwingend) auf die selbe Ziel-URL verweisen.
+ Insbesondere Medienproduzenten und **institutionelle Bildungsmedienanbieter weisen unterschiedliche Zielgruppen – so z.B. die jeweiligen Bildungsserver der verschiedenen Bundesländer auf dasselbe Angebot hin**. Dieses Angebot wird dann – oft bloß selektiv und aus je verschiedenen Perspektiven – in z.B. landeseigenen Systemen mit Metadasten erfasst. Diese Systeme stehen zunehmend im (Metadaten-) Austausch miteinander.

**Im Effekt ergeben sich in beiden Fällen also mehrere gleichartige Datensätze zum selben Inhalt**.
Dies hat zumindest einen positiven und einen negativen Aspekt:

+ Der **negative Aspekt** ergibt sich, wenn ein Portal für Unterrichtsmedien (oder Metadaten-Aggregatoren selbst) Daten aus verschiedenen Quellen beziehen. 
   + Der Endanwender bekommt in der Suche **mehrere Treffer zum selben Inhalt**
   + Bei Systemen mit Sammlungsfunktion ergibt sich ein zusätzliches Problem, wenn ein Datensatz A1 schon in einer Sammlung verwendet wird, dieser aber durch den Datensatz A2 esrsetzt wird bzw. werden soll, weil dessen Metadaten geeigneter erscheinen ... und wieder später durch A3. **Durch ein bloßes Ersetzen würde die bestehende Sammlung unbrauchbar, wie z.B. auch Einbindungen von Inhalten (über deren ID) in angeschlossene Lernmanagemntsysteme**.

+ Ein **positiver Aspekt** ähnlicher – jedoch aus unterschiedlichen pädagogisch-fachlichen Perspektiven – erstellten Datensätzen ist, dass diese Aspekte sich womöglich zu einem **höherwertigen Datensatz _mergen_ **lassen.
+ Ebenso dürfte das Wissen um die Identität oder Gleichartigkeit verschiedener Datensätze aus verschiedenen Quellen für das **Anlernen von KI** nützlich sein – zumal bei redaktioneller Metadatengenerierung aus multiplen Perspektiven.

**Comment by acka47** [comment]
In OERSI hatten wir gerade einen ähnlichen Fall mit BCCampus, siehe https://gitlab.com/oersi/oersi-etl/-/issues/185#note_1199028952. Das haben wir aber nicht mit ''sameAs'' gelöst, sondern indem die BCCampuns-Kolleg:innen `isBasedOn`-Links auf die Originalquelle gesetzt haben. Wir nutzen dann diesen Link zur kanonischen Version als `id` und packen den Link zur Landing Page der BCCampus-Version in `mainEntityOfPage.id`, was ich eigentlich eine gut Lösung finde.  Das funktioniert auf jeden Fall gut in Fällen, wo es eine kanonische Version gibt und auch klar ist, welche das ist.

**Comment by acka47** [comment]
> @bokahama wird nun schauen, ob dieser Ansatz auch für seinen konkreten Problemfall eine Lösung sein kann.

Wie gerade im Gruppentreffen besprochen, reicht der Ansatz reicht aus für den Anwendungsfall, weshalb ich das Ticket schließe.
