### ISSUE TITLE
Ergänzung von `interactivityType` (Lehr-/Lernform)

### ISSUE THREAD

**Issue by ComeIn-NRW** [dini-ag-kim/amb#170]
**Werte**

- active: "Lernen, welches das Denken des Lernenden in realen und/oder imaginären Situationen anregt und herausfordert und dabei die Lernmöglichkeiten nutzt, die sich durch Untersuchungen, Erkundungen, Ereignisse und Erfahrungen ergeben."
- expositive: "Einsatz eines Lehrenden zur Erklärung eines Konzepts oder zur zielgerichteten Vermittlung klarer und prägnanter Informationen an den Lernenden."
- mixed: "Unterrichtliche Interaktionen, die eine Mischung aus aktivem Lernen (eher selbstgesteuert) und erklärenden Ansätzen (eher fremdgesteuert) beinhalten."

Feldspezifikationen der LRMI
- TTL: https://www.dublincore.org/vocabs/interactivityType.ttl
- https://www.dublincore.org/specifications/lrmi/concept_schemes/interactivityType/
- https://www.dublincore.org/specifications/lrmi/lrmi_terms/2020-11-12/#interactivityType

**Ziele**, u.a.:
- Kennzeichnung / Differenzierung von Selbstlernmaterial:
Kann ein Lerner das Material selbstständig zum Erreichen der ausgewiesenen Lernziele nutzen oder ist eine Unterstützung/Erläuterung, z.B. durch einen Lehrenden erforderlich, bspw. für Lerner auf dem erwarteten Niveau idR “unverständliche” Präsentationen - da bpsw, ohne Skript / Erläuterungen; Grafiken, die erläuterungsbedürftig sind, etc.

- Materialien besonders hervorheben, die autonom verwendet werden können, um damit zu lernen (idR aber “größere” Einheiten): Welche Materialien können zum Erreichen der ausgewiesenen Lernziele autonom verwendet werden?

**Use cases** (Beispiele)
- Lerner, die in einem Portal nach selbstständig nutzbaren Materialien suchen, die keinem Lehrenden bedürfen (z. B. Studierende für eigene Ausbildung, Lehrkräfte für eigene Fortbildung, …)

- Lehrende, denen die Info auch helfen würde, da sie bspw. Aufgaben/Aktivitäten für Zuhause; bestimmte Methoden/Konzepte wie Flipped Classroom o.ä. bzw. für bestimmte Phasen (Vertiefung/Erarbeitung) finden könnten; vor allem auch, wenn es z.B. Wochenplanarbeit / Freiarbeit o.ä. ist (und somit ggf. kein qualifizierter Fachlehrer vor Ort unterstützen kann)

**Referenzen**
- [schema.org ](https://schema.org/interactivityType)
- LOM (5.1)

**Comment by acka47** [comment]
To Do für @ComeIn-NRW aus dem letzten Treffen: PR öffnen, so dass wir uns den Vorschlag in Spec-Form anschauen können.
