### ISSUE TITLE
Ordnung der Attribute in AMB zur Herstellung besserer Übersichtlichkeit

### ISSUE THREAD

**Issue by sroertgen** [dini-ag-kim/amb#173]
Hallo zusammen,

zur Herstellung einer besseren Übersichtlichkeit halte ich es für sinnvoll, dass wir die Attribute im AMB thematisch sortieren.

Generell zur Sortierung innerhalb der Kategorien: 
- zunächst Pflichtattribute
- anschließend optionale Attribute

Ich schlage außerdem vor, nicht alphabetisch zu sortieren, sondern eher thematisch, um thematisch verwandte Attribute (e.g. `assesses`, `competencyRequired`, `teaches`) nacheinander zu beschreiben.

Vorschlag zur Diskussion:

- Allgemein
  - `@context`
  - `id`
  - `type`
  - `name`
  - `description`
  - `about`
  - `keywords`
  - `inLanguage`
  - `image`
  - `trailer`
- Provenienz? / Entstehung?
  - `creator`
  - `contributor`
  - `affiliation`
  - `dateCreated`
  - `datePublished`
  - `publisher`
- Kosten und Rechte
  - `license`
  - `conditionsOfAccess`
  - `isAccessibleForFree`
- Pädagogisch
  - `learningResourceType`
  - `audience`
  - `assesses`
  - `competencyRequired`
  - `teaches`
  - `educationalLevel`
- Relation
  - `isBasedOn`
  - `hasPart` 
  - `isPartOf`
- Metametadata
  - `mainEntityOfPage`
- Technical
  - `caption`
  - `duration`
  - `encoding`

Was haltet ihr davon? @acka47 @oellers

**Comment by oellers** [comment]
Die Idee unterstützt ich grundsätzlich und halte sie für die erste Version auch umsetzbar. Einzig wäre ggf. problematisch, dass sich bei einer neuen Version die Identifier ändern (z. B. würde aus 4.21 für learningResourceType dann ggf. 4.22, wenn davor etwas eingefügt würde); die Perma-URIs von ReSpec gehen jedoch weiterhin.

Kategorien könnten sich ggf. an LOM(-CH) und/oder dem [LOM for Higher Education OER Repositories-Profil](https://dini-ag-kim.github.io/hs-oer-lom-profil/latest/) orientieren.

[LOM-CH v2.1](https://www.educa.ch/sites/default/files/2020-11/applikationsprofil-lom-ch-v2.1-de.pdf):
> 1. Allgemeine Informationen: Enthält allgemeine Informationen über das Lernobjekt (Titel, Sprache,
> Zusammenfassung, Schlagworte, ...)
> 2. Lebenszyklus: Informiert über Eigenschaften und Angaben zur Geschichte und zum aktuellen
> Zustand des Lernobjektes (Version, Autoren, Personen oder Organisationen, die einen Beitrag zur
> Ressource geleistet haben, ...)
> 3. Meta-Metadata: Enthält Informationen über die Metadaten selbst (Verfasser der Metadaten,
> Sprache, Datum der Erfassung, ...)
> 4. Technische Informationen: Enthält die technischen Anforderungen sowie die technischen Daten
> des Lernobjekts (Format, Dateigrösse, technische Voraussetzungen, ...)
> 5. Pädagogische Informationen: Beschreibt die für den Unterricht wichtigen Eigenschaften eines
> Lernobjekts (Zielgruppen, durchschnittliche Lernzeit, Schwierigkeitsgrad, semantische Dichte, ...)
> 6. Urheberechte: Liefert Informationen bezüglich Urheberrechts- und Nutzungsbedingungen des
> Lernobjekts (Lizenzrechte und -Bedingungen, Kosten, ...)
> 7. Beziehung: Beschreibt die Beziehungen zu anderen Lernobjekten (Beziehungsart, Identifikation der
> Zielressource, ...)
> 8. Kommentar: Erlaubt Anmerkungen und zusätzliche Kommentare zum Lernobjekt und zur Nutzung
> desselben (wann, von wem)
> 9. Klassifikation: Beschreibt die Beziehung des Lernobjekts zu anderen, externen Klassifikationssystemen (Klassifikation, Zweck, ...)
> 10. Curricula: Angaben zu den verschiedenen Schul- und Ausbildungslehrplänen.
> 11. Barrierefreiheit: Spezifische Angaben bezüglich der Zugänglichkeit einer Ressource

**Comment by acka47** [comment]
> Einzig wäre ggf. problematisch, dass sich bei einer neuen Version die Identifier ändern (z. B. würde aus 4.21 für learningResourceType dann ggf. 4.22, wenn davor etwas eingefügt würde);

Das ist m.E. unproblematisch, handelt es sich doch nur um die Abschnittsnummerierung. "Identifier" für einzene AMB-Properties wären ja eher so etwas wie https://w3id.org/kim/amb/latest/#learningresourcetype. (Die schreiben wir aber nirgends hin, was wir auch nochmal überlegen könnten. Wäre cool, wenn die hinter den `§` liegenden Sprungmarken (`id`-Links) diie w3id als Basis-URL nehmen könnten...) Auch die URIs zum jeweiligen Schema könnten als Identifier genutzt werden, z.B. `https://w3id.org/kim/amb/latest/schemas/learningResourceType.json`
