### ISSUE TITLE
Publikationsreihe / Serientitel als weiteres Attribut

### ISSUE THREAD

**Issue by bokahama** [dini-ag-kim/amb#174]
Die Einführung _eines_ Feldes ins AMB scheint aus wenigstens zwei Gründen wichtig:

a) In der klassischen _Mediendstribution im Schulbereich_ finden sich häufiger **Serientitel** (EAF-Systematik, Feld **D10,** bzw. D14, D16). Einige Distributionssysteme nutzen diesen Eintrag um Publikationen zu bündeln bzw. 'Vorschläge' zu generieren

b) Im (digitalen) _Schulbuchbereich_ ist das Wissen um die Publikationsreihe besonders wichtig, z.B. im Sprachunterricht, wo Lehrwerke und Übungswerke sich aufeinander beziehen. 

Anbei ein Beispieldatensatz aus DaBi – dem zentrale Verzeichnis der Länder für 'klassische Bildungsmedien' : <https://dabi.fwu.de/edu-sharing/components/render/bc26e99d-755b-4970-a22d-67fbc875a734> 

Die folgende Datei hat beim Download aus der DaBi die Endung .eaf
[BWS-055503545.txt](https://github.com/dini-ag-kim/amb/files/10434225/BWS-055503545.txt)

Die Spezifikation des EAF-Formats findet sich hier: <http://agmud.de/wp-content/uploads/2021/09/db-eaf.pdf>

**Comment by bokahama** [comment]
@acka47 bemerkte im Meeting, dass wir den Wert aus schema.org nutzen könnten <https://schema.org/CreativeWorkSeries>

Dabei wird meinem Verständnis nach auch die Relation eingetragen, sodass es zur Publikationsreihe selbst auch eines Datensatzes bedürfte.

Vielleicht könnte man im ersten Schritt auf die (zwingende) Abbildung der Relationen verzichten – auch um die DaBi-Datensätze abbilden zu können.

**Comment by acka47** [comment]
> @acka47 bemerkte im Meeting, dass wir den Wert aus schema.org nutzen könnten https://schema.org/CreativeWorkSeries
>
> Dabei wird meinem Verständnis nach auch die Relation eingetragen, sodass es zur Publikationsreihe selbst auch eines Datensatzes bedürfte.

Tatsächlich ist https://schema.org/CreativeWorkSeries eine Typ-Angabe und keine Relation, d.h. sie könnte zur Typisierung der Publikationsreihe als eine solche verwendet werden. Für die Relation würde selbst `isPartOf`/`hasPart` genutzt werden. Das könnte dann konkret etwa so aussehen:

```json
{
   "id":"https://dabi.fwu.de/edu-sharing/components/render/bc26e99d-755b-4970-a22d-67fbc875a734",
   "name":"Deutsche Revolution 1848/49",
   "type":[
      "LearningResource",
      "VideoObject"
   ],
   "learningResourceType":[
      {
         "id":"https://w3id.org/kim/hcrt/video",
         "prefLabel":{
            "de":"Video",
            "en":"Video"
         }
      }
   ],
   "isPartOf":{
      "type":"CreativeWorkSeries",
      "name":"Geschichte interaktiv"
   }
}
```

Wie man sieht, muss nicht extra ein Seriendatensatz angelegt werden, sondern die Serie lediglich als eigenes Objekt – falls nicht vorhanden eben ohne `id` – eingetragen werden.

**Comment by bokahama** [comment]
Gut – dann spricht m.E. nichts dagegen, das Feld einzuführen um z.B. DaBi-Datensätze über das AMB-Profil abzubilden.

(Hatte es übrigens mehr als policy-Wunsch deinerseits (denn als technische Bedingung) verstanden, sofort mit Relationen und eben IDs zu arbeiten.)

**Comment by acka47** [comment]
> Gut – dann spricht m.E. nichts dagegen, das Feld einzuführen um z.B. DaBi-Datensätze über das AMB-Profil abzubilden.

Jetzt hat @axel-klinger in #175 noch eine weitere Anforderung eingebracht und zwar die Angabe der Reihenfolge/Nummerierung. Den hier diskutierten Ansatz könnte man gut mit der in schema.org vorhandenen  generische Property [`sdo:position`](https://schema.org/position) bzw. über deren Sub-Properties [`sdo:clipNumber`](https://schema.org/clipNumber), [`sdo:episodeNumber`](https://schema.org/episodeNumber), [`sdo:issueNumber`](https://schema.org/issueNumber), [`sdo:seasonNumber`](https://schema.org/seasonNumber), [`sdo:volumeNumber`](https://schema.org/volumeNumber) erweitern.

**Comment by acka47** [comment]
> Gut – dann spricht m.E. nichts dagegen, das Feld einzuführen um z.B. DaBi-Datensätze über das AMB-Profil abzubilden.

Das Feld `isPartOf` gibt es bereits, siehe https://dini-ag-kim.github.io/amb/draft/#ispartof. Von daher müsstne wir nichts ergänzen. Für die Type-Angabe gibt es keine Beschränkungen. In der Spec wird lediglich gesagt, dass `isPartOf` auf "andere Ressourcen" verwest. Somit gilt implizit, das das gesamte Profil wiederum auf die verlinkten Ressourcen angewendet werden kann. Zu [`type`](https://dini-ag-kim.github.io/amb/draft/#type) heißt es darin:

> MUSS den Wert LearningResource enthalten. KANN weitere Werte aus den Unterklassen von https://schema.org/CreativeWork enthalten.

`CreativeWorkSeries` ist eine Unterklasse von https://schema.org/CreativeWork. Somit ist der Anwendungsfall durch das Profil bereits voll abgedeckt und wir müssen nichts ergänzen. (Evtl. sollten wir im Treffen mal überlegen, ein paar Anwendungsregeln/Beispielmetadaten struzkturiert zur Verfügung zu stellen, wo eben auch die Erfassung einer Serie und der Relation zu ihr beschrieben werden kann.)

> Den hier diskutierten Ansatz könnte man gut mit der in schema.org vorhandenen generische Property [sdo:position](https://schema.org/position) bzw. über deren Sub-Properties [sdo:clipNumber](https://schema.org/clipNumber), [sdo:episodeNumber](https://schema.org/episodeNumber), [sdo:issueNumber](https://schema.org/issueNumber), [sdo:seasonNumber](https://schema.org/seasonNumber), [sdo:volumeNumber](https://schema.org/volumeNumber) erweitern.

Wie in https://github.com/dini-ag-kim/amb/issues/175#issuecomment-1401932886 geschrieben, haben wir uns erstmal drauf geeinigt von Angaben zur Reihenfolge/nummerierung vorerst abzusehen.

Vor diesem Hintergrund denke ich, dass wir dieses Ticket schließen können. Was meinst du, @bokahama ?

**Comment by bokahama** [comment]
Ja, so betrachtet ist alles Nötige drin und wir können das Ticket schließen.
Unter CreativeWorkSeries können die Werte ja noch ausgestaltet werden.
