### ISSUE TITLE
Strukturinformationen für Serienelemente

### ISSUE THREAD

**Issue by axel-klinger** [dini-ag-kim/amb#175]
Neben den hierarchischen Beziehungen `isPartOf` und `hasPart` fehlt mE noch eine Beschreibung von Vorgängern und Nachfolgern in Serien bzw. auch die Abbildung der Reihenfolge bei hierarchischen Strukturen. Wenn die Lektionen eines Kurses oder die Elemente einer Lektion oder die Elemente einer Videoserie nur mit isPart zugeordnet werden, wären die Parts des übergeordneten Obejkts nur eine ungeordnete Menge. Vorschlag: die Beziehungen der Vorgänger (Predecessor) und Nachfolger (Successor) über `isPredOf` / `hasPred` und `isSuccOf` / `hasSucc` beschreiben.

**Comment by acka47** [comment]
> Vorschlag: die Beziehungen der Vorgänger (Predecessor) und Nachfolger (Successor) über `isPredOf` / `hasPred` und `isSuccOf` / `hasSucc` beschreiben.

In schema.org gibt es momentan nur die "is..Of"-Variante:
- [`sdo:successorOf`](https://schema.org/successorOf)
- [`sdo:predecessorOf`](https://schema.org/predecessorOf)

Wie auch immer, schema.org sieht ohnehin eher vor, die Nummerierung zu verwenden, um die Reihenfolge von Serienelementen darzustellen. Dies geschieht entweder über die generische Property [`sdo:position`](https://schema.org/position) oder über deren Sub-Properties [`sdo:clipNumber`](https://schema.org/clipNumber), [`sdo:episodeNumber`](https://schema.org/episodeNumber), [`sdo:issueNumber`](https://schema.org/issueNumber), [`sdo:seasonNumber`](https://schema.org/seasonNumber), [`sdo:volumeNumber`](https://schema.org/volumeNumber). Siehe auch den Blogpost ["Schema.org Support for Bibliographic Relationships and Periodicals"](http://blog.schema.org/2014/09/schemaorg-support-for-bibliographic_2.html) von Richard Wallis.

Ich würde mich über einen konreten Use Case freuen, der hier mal beispielhaft umgesetzt werden kann, damit das keine theoretische Übung bleibt.

**Comment by acka47** [comment]
Siehe auch #174, wo es nur um die Serieninformation ohne Strukturelemente geht.

**Comment by axel-klinger** [comment]
Hier zwei Beispiele zum testen:

* AV-Portal Serie https://av.tib.eu/series/618/basiswissen+physik
* edu-sharing Sammlung https://www.oerbw.de/edu-sharing/components/collections?viewType=1&id=1a053dc6-64a9-4462-9c32-7f2522e4ecfc

Weitere Beispiele wären auch die Kurse des MIT mit ihren Einzelelementen.

**Comment by axel-klinger** [comment]
Eine Nummerierung mit position bildet das zwar auch ab, aber um später eine Navigation zu ermöglichen könnte pred/succ effizienter sein.

**Comment by acka47** [comment]
Ich weiß nicht, ob so etwas im Bereich Bildungsressourcen passiert, möchte aber der Vollständigkeit halber bei dieser Diskussion darauf hinweisen. Bei der Neu-Modelliering der lobi-Metadaten 2014/15 mussten wir auch Ressourcen korrekt abbilden, die gleichzeitig zu zwei Serien gehören und jeweils unterschiedliche Nummerierung pro Serie haben oder aber solche, die gleichzeitig Band X eines mehrbändigen Werkes sind _und_ Teil einer Serie.

Beides ließe sich weder mit `position` noch mit pred/succ abbilden. Wir haben das dann bei lobid gelöst durch die Anwendung von "another level of indirection" ([David Wheeler](https://en.wikipedia.org/wiki/David_Wheeler_(computer_scientist)#Quotes)).

Das sieht dann zum [Beispiel](https://lobid.org/resources/HT002888677.json) so aus:

```json
{
   "isPartOf":[
      {
         "type":[
            "IsPartOfRelation"
         ],
         "hasSuperordinate":[
            {
               "id":"http://lobid.org/resources/HT002888668#!",
               "label":"lobid Ressource"
            }
         ],
         "numbering":"2"
      },
      {
         "type":[
            "IsPartOfRelation"
         ],
         "hasSuperordinate":[
            {
               "id":"http://lobid.org/resources/HT001236717#!",
               "label":"Schriften des Zentralinstituts für Geschichte"
            }
         ],
         "numbering":"73"
      }
   ]
}
```

Gerne würde ich das AMB aber einfach halten und auf eine solche Modellierung verzichten.

**Comment by acka47** [comment]
@axel-klinger und haben gerade in Anwesenheit von @mirjan-hoffmann und @TobiasNx im OERSI-Treffen abgesprochen, dass wir zunächst die existierende Möglichkeit nutzen, die Zugehörigkeit einer Ressource zu einer Serie oder einem Kurs mit `isPartOf` zu erfassen. Siehe zur Anwendung auch #174. Dieses Ticket schließe ich damit vorerst.
