### ISSUE TITLE
Klärung der Property "id"

### ISSUE THREAD

**Issue by pajoma** [dini-ag-kim/amb#183]
Im Draft wird auf die Property "@Context" verwiesen, aber nicht auf "@id". Es wäre für das Verständnis hilfreich, die folgende Properties voneinander abzugrenzen: 

* die "@id" ist der [Node-Identifier](https://w3c.github.io/json-ld-syntax/#node-identifiers) und sollte die URI enthalten, die auf das Metadatendokumenten selbst verweist (Beispiel: http://me.markus-lanthaler.com/) 
* die "id" laut Spec die URI, durch den die Ressource identifiziert wird. Ich nehme an, mit "Ressource" ist hier die LearningRessource gemeint, nicht das Metadatendokument. 
* der "identifier" aus schema.org als eindeutiger Identifier für die Ressource (entspricht von der Logik der AMB-"id", aber muss keine URI sein
* die "url" aus schema.org als url des Items (also Ressource, also eigentlich "id" aus dem AMB Draft) 

Ein ähnliches Problem sehe ich bei "type". Da ist im [Schema ](https://dini-ag-kim.github.io/amb/draft/schemas/type.json) allerdings definiert, dass auch @type gültig ist, oder?

Das folgende Beispiel illustriert das denke ich nochmal ganz gut: 

```json

{
  "@context": {
     "amb": "https://w3id.org/kim/amb/context.jsonld",
     "sdo" : "https://schema.org"
  },
  "@id": "http://www.acme.com/123231/metadata.jsonld",
  "amb:id": "http://www.acme.com/123231", 
  "sdo:url": "http://www.acme.com/123231/web", 
  "sdo:identifier": "http://www.acme.com/123231"
  "@type": [ "sdo:LearningResource", "sdo:Article" ], 
  "amb:type": [ "sdo:LearningResource", "sdo:Article" ], 
}
```

**Comment by acka47** [comment]
Hallo @pajoma, danke für deine Rückmeldung.

> Im Draft wird auf die Property `@context` verwiesen, aber nicht auf `@id`

Du hast Recht, das JSON-LD-Keyword ist im Draft nicht driekt enthalten, allerdings ist es identisch mit `id`, weil im Kontext ein entsprechender Alias gesetzt wird, siehe https://dini-ag-kim.github.io/amb/context.jsonld_

```json
{

    "@context": {
        "id": "@id",
        "type": "@type",
        "@vocab": ["http://schema.org/"](http://schema.org/),
        "skos": ["http://www.w3.org/2004/02/skos/core#"](http://www.w3.org/2004/02/skos/core#),
        "prefLabel": {
            "@id": "skos:prefLabel",
            "@container": "@language"
        },
        "inScheme": "skos:inScheme",
        "Concept": "skos:Concept"
    }
}
```

Im schema.org-JSON-LD-Kontext ist dieser Alias übrigens auch gesetzt, weshalb das redundant ist, siehe dazu https://github.com/schemaorg/schemaorg/issues/854.

Schau dir also bitte nochmal die Beschreibung von `id` an (https://dini-ag-kim.github.io/amb/draft/#id) und gib gerne Feedback, wenn das noch verbessert werden soll. Im Kontext von https://github.com/dini-ag-kim/amb/issues/153 hatten wir da bereits nachgearbeitet.

**Comment by pajoma** [comment]
Danke für die Klärung. Dann ist aber der folgende Text irreführend aus der Spec für die Property "id"

> Der URI, durch den die Ressource identifiziert wird. Der URI KANN direkt zur Ressource auflösen oder zu einer Landing Page, auf der die Ressource beschrieben und verlinkt ist.

Die ID **muss** als Node Identifier auf das Metadatendokument selbst verweisen. Es kann niemals auf eine Landing Page verweisen. 

> dereferencing the identifier should result in a representation of that [node](https://www.w3.org/TR/rdf11-concepts/#dfn-node).
https://www.w3.org/TR/json-ld11/#node-identifiers

**Comment by kulla** [comment]
Hey @pajoma Dank dir für deine Nachricht! Zu deiner ursprünglichen Frage: Zunächst müssen wir beachten, dass IRIs keine URIs sein müssen. Hier geht auch https://www.w3.org/TR/json-ld11/#iris direkt ein:

> As noted in [§ 1.1 How to Read this Document](https://www.w3.org/TR/json-ld11/#how-to-read-this-document), IRIs can often be confused with URLs ([Uniform Resource Locators](https://www.w3.org/TR/ld-glossary/#uniform-resource-locator)), the primary distinction is that a URL locates a resource on the web, an IRI identifies a resource. While it is a good practice for resource identifiers to be dereferenceable, sometimes this is not practical.

Beispielsweise kann eine [URN](https://www.rfc-editor.org/rfc/rfc2141) wie `urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6` angegeben werden. Ich könnte mir vorstellen, dass dies bei Bildungsresourcen sinnvoll ist, die keine eindeutige Webadresse haben. AMB sollte aber IMHO eine eindeutige URI stets empfehlen.

Zum anderen kann [JSON-LD auch direkt in Webseiten integriert werden](https://www.w3.org/TR/json-ld11/#embedding-json-ld-in-html-documents). Ein Beispiel ist die `@id` https://schema.org/name. Am Ende des HTMLs befindet sich:

```html
<script type="application/ld+json">
{
  "@context": {
    "brick": "https://brickschema.org/schema/Brick#",
    "csvw": "http://www.w3.org/ns/csvw#",
    "dc": "http://purl.org/dc/elements/1.1/",
    "dcam": "http://purl.org/dc/dcam/",
    "dcat": "http://www.w3.org/ns/dcat#",
    "dcmitype": "http://purl.org/dc/dcmitype/",
    "dcterms": "http://purl.org/dc/terms/",
    "doap": "http://usefulinc.com/ns/doap#",
    "foaf": "http://xmlns.com/foaf/0.1/",
    "geo": "http://www.opengis.net/ont/geosparql#",
    "odrl": "http://www.w3.org/ns/odrl/2/",
    "org": "http://www.w3.org/ns/org#",
    "owl": "http://www.w3.org/2002/07/owl#",
    "prof": "http://www.w3.org/ns/dx/prof/",
    "prov": "http://www.w3.org/ns/prov#",
    "qb": "http://purl.org/linked-data/cube#",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "schema": "https://schema.org/",
    "sh": "http://www.w3.org/ns/shacl#",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "sosa": "http://www.w3.org/ns/sosa/",
    "ssn": "http://www.w3.org/ns/ssn/",
    "time": "http://www.w3.org/2006/time#",
    "vann": "http://purl.org/vocab/vann/",
    "void": "http://rdfs.org/ns/void#",
    "wgs": "https://www.w3.org/2003/01/geo/wgs84_pos#",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@id": "schema:name",
  "@type": "rdf:Property",
  "owl:equivalentProperty": {
    "@id": "dcterms:title"
  },
  "rdfs:comment": "The name of the item.",
  "rdfs:label": "name",
  "rdfs:subPropertyOf": {
    "@id": "rdfs:label"
  },
  "schema:domainIncludes": {
    "@id": "schema:Thing"
  },
  "schema:rangeIncludes": {
    "@id": "schema:Text"
  }
}
</script>
``` 

Wenn also die URI auf eine Landing Page verweist, dann sollte diese ein JSON-LD enthalten. IMHO schreibt die Spezifikation dies aber nicht vor. Dies steht ja auch in der von dir verlinkten Definition (hier steht ein "should" und kein "must"):

> To be able to externally reference [nodes](https://www.w3.org/TR/rdf11-concepts/#dfn-node) in an [RDF graph](https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-graph), it is important that [nodes](https://www.w3.org/TR/rdf11-concepts/#dfn-node) have an identifier. [IRIs](https://www.rfc-editor.org/rfc/rfc3987#section-2) are a fundamental concept of Linked Data, for [nodes](https://www.w3.org/TR/rdf11-concepts/#dfn-node) to be truly linked, dereferencing the identifier **should** result in a representation of that [node](https://www.w3.org/TR/rdf11-concepts/#dfn-node).

Es sollte aber als ein Best Practice hervorgehoben werden, dass `id` eine eindeutige URI ist, die entwender direkt auf ein `application/json+ld` verweist oder die eine Ressource enthält, aus der das JSON-LD herausgeladen werden kann (siehe auch https://www.w3.org/TR/json-ld11-api/#remote-document-and-context-retrieval)

**Comment by acka47** [comment]
> Zunächst müssen wir beachten, dass IRIs keine URIs sein müssen

Ja, und URIs müssen keine HTTP-URIs sein und die wiederum keine URLs. Ich würde es so zusammenfassen:

- IRIs und URIs sind sehr ähnlich, erstere unterstützen das komplette Universal Coded Character Set (UCS).
- HTTP-URIs sind eine Untermenge der URIs und können auch zur bloßen Identifizierung von Dingen verwendet werden, ohne dass die URI resolvt.
- URLs sind HTTP-URIs, die auf ein Dokument (HTML, JSON etc.) resolven.

In der Spec wollten wir bisher solche Feinheiten nicht behandeln, es würde viele auch verwirren. Wir gehen eher im Sinne von Linekd Data davon aus, dass HTTP-URIs als Identifikatoren verwendet werden, die auch auf die Lernressource bzw. deren Metadaten/Landing Page resolven.

> Wenn mit der Ressource die Metadaten Ressource selbst gemeint ist, würde ich das auch entsprechend so schreiben. 
>
>> Eine dereferenzierbare IRI, welche diese Ressource eindeutig identifiziert. Der IRI KANN als URL direkt zu der Ressource auflösen oder (KANN/MUSS?) auf eine Landing Page verweisen, welche die Ressource **enthält**.

Ich bin mir nicht sicher, was du mit "Metadaten Ressource" meinst. Ich würde so das Metadatendokument, d.h. die Beschreibung der Bildungsressource bezeichnen, habe aber den Eindruck, dass du etwas anderes meinst. Evtl. Ist das aber auch nicht so wichtig.

Generell haben wir bisher "URI" und nicht "IRI" in der Spec genutzt und sollten glaube ich auch dabei bleiben. Der derzeitigen Praxis im deutschsprachigen Raum wird es m.E. gerecht.

Deinen Hinweis, dass der Ausdruck "Ressource" hier nicht klar ist, finde ich wichtig. "Ressource" kommt sehr häufig im Dokument vor. Ich denke, wir sollten es sinnvollerweise durch "Bildungsressource" ersetzen und zwar überall dort, wo es nicht absichtlich allgemeiner im Sinne von "Webressource" benutzt wird.

Abschließend noch zu @kulla's Punkt:

> Es sollte aber als ein Best Practice hervorgehoben werden, dass `id` eine eindeutige URI ist, die entwender direkt auf ein `application/json+ld` verweist oder die eine Ressource enthält, aus der das JSON-LD herausgeladen werden kann 

Meines Erachtens haben wir das im [Abschnitt "Format und Bereitstellung"](https://dini-ag-kim.github.io/amb/draft/#format) hinreichend geklärt. Falls nicht, freue ich mich über konkrete Verbesserungsvorschläge.

**Comment by acka47** [comment]
Im Prinzip soll die Spec auf einfache Weise erklären, wie ich Bildungsressourcen mit strukturierten Daten beschreibe. Dass die Daten am Ende Linked-Data-konform sind, ist nur ein schöner Nebeneffekt... Evtl. wäre es sinnvoll, zukünftig  einen gesonderten Abschnitt "AMB-Daten als RDF/Linked Data" oder Ähnliches hinzuzufügen, in dem wir auf die technischen Details im Hinblick auf LOD-Kompatibilität eingehen. Ich glaube aber, dass das nur einen sehr kleinen Teil der potentiellen Zielgruppe interessiert...

**Comment by pajoma** [comment]
> Ich bin mir nicht sicher, was du mit "Metadaten Ressource" meinst. Ich würde so das Metadatendokument, d.h. die Beschreibung der Bildungsressource bezeichnen, habe aber den Eindruck, dass du etwas anderes meinst. Evtl. Ist das aber auch nicht so wichtig.

In diesem Fall beziehe mich auf das Metadatendokument, oder wie in 3.2 "metadaten als eigene Webressource"

Neuer Vorschlag 

> Eine dereferenzierbare URI, welche diese Ressource eindeutig identifiziert. Der URI KANN als URL direkt zu der Webressource der Metadaten auflösen oder auf die Webseite verweisen, welche die Metadaten gemäß §3 eingebettet oder verknüpft hat.

**Comment by acka47** [comment]
Danke für den Vorschlag, @pajoma . Jetzt bin ich mir nicht sicher, worauf du dich mit "Webressource der Metadaten" beziehst. Wie auch immer, ich habe deinen Vorschlag aufgenommen und ein wenig angepasst und schlage folgende Variante vor:

```html
Ein dereferenzierbarer HTTP-URI, welcher die Bildungsressource eindeutig identifiziert. 
Der URI KANN als URL direkt zur Bildungsressource auflösen oder auf eine beschreibende 
Webseite (Landing Page) verweisen (vgl. Abschnitt <a href="#format">Format und Bereitstellung</a>).
```
Ich habe das mal in https://github.com/dini-ag-kim/amb/pull/187/commits/2e158ba28284316c1fa7c8173234f62c93326a9b umgesetzt und in dem PR #187 auch mal die "Ressourcen"-Terminologie aus https://github.com/dini-ag-kim/amb/issues/183#issuecomment-1468216790 aufgegriffen (Vereinheitlichung auf "Bildungsressource"). Würde das für dich so passen?

**Comment by acka47** [comment]
@pajoma Es wäre super, wenn du dir mal #187 anschauen könntest. Ich kann dich leider nicht assignen, weil du (noch) nicht in der KIM-GitHub-Organisation bist...

**Comment by acka47** [comment]
Ich habe #187 jetzt gemergt und mache das Ticket hier zu.
