### ISSUE TITLE
`id` bei `publisher` hinzufügen

### ISSUE THREAD

**Issue by kulla** [dini-ag-kim/amb#192]
Bisher ergänzen wir konsequent `id` bei referenzierten Objekten. Beispiele hierfür sind [`learningResourceType`](https://dini-ag-kim.github.io/amb/draft/#dfn-learningresourcetype) und [`license`](https://dini-ag-kim.github.io/amb/draft/#dfn-license). Bei [`publisher`](https://dini-ag-kim.github.io/amb/draft/#dfn-publisher) fehlt eine Angabe zu `id`. Diese würde ich zumindest als SOLL der Spezifikation hinzufügen, damit auch dieses Objekt eine eindeutige IRI im Sinne von JSON-LD erhält.

**Comment by oellers** [comment]
Inwiefern fehlt eine Angabe zu id? Im Beschreibungstext der HTML Spezifikation? Das [JSON Schema für _publisher_](https://dini-ag-kim.github.io/amb/draft/schemas/publisher.json) sieht eine id als URI vor. Ich würde das Feld vergleichen mit affiliation oder creator, dort ist auch nur type und name erforderlich.

Idee dahinter war vermutlich, dass nicht jedes Objekt, z .B. Personen, eindeutig identifiziert werden kann (wenn sie bspw. keine ORCID o.ä. haben)

Vielleicht sollten wir jedoch generell alle empfohlenen properties von Objekten dokumentieren, damit auch in den HTML Spezifikationen bereits ersichtlich ist, was das JSON Schema enthält.

**Comment by kulla** [comment]
> Inwiefern fehlt eine Angabe zu id? Im Beschreibungstext der HTML Spezifikation?

Genau, das ist mit diesem Issue gemeint.

> Vielleicht sollten wir jedoch generell alle empfohlenen properties von Objekten dokumentieren, damit auch in den HTML Spezifikationen bereits ersichtlich ist, was das JSON Schema enthält.

:+1:
