### ISSUE TITLE
Eindeutige `id` bei `license` vorschreiben?

### ISSUE THREAD

**Issue by kulla** [dini-ag-kim/amb#193]
Mir ist aufgefallen, dass nach unserer Definition `id` unterschiedliche Werte bei `license` haben kann, selbst wenn es auf dieselbe Lizenz verweist. So sind folgende URIs valide Werte für [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/):

```
http://creativecommons.org/licenses/by-sa/4.0/
https://creativecommons.org/licenses/by-sa/4.0/
https://creativecommons.org/licenses/by-sa/4.0/deed.en
https://creativecommons.org/licenses/by-sa/4.0/deed.de
```

Wenn man mit [dem schema.org Validator obige URIs auflöst](https://validator.schema.org/#url=http%3A%2F%2Fcreativecommons.org%2Flicenses%2Fby-sa%2F4.0%2F), dann erhält man als `id` den Wert `https://creativecommons.org/licenses/by-sa/4.0/deed.id`. Sofern auch andere Lizenzen eine eindeutige `@id` haben (habe ich noch nicht geprüft): Sollten wir in AMB genauer vorgeben oder empfehlen, welche Werte für die Lizenz angegeben werden soll? So könnten Konsumenten die Lizenz einfacher parsen.

**Comment by kulla** [comment]
Sidenote: Ich bin mir unsicher, ob `@id` in JSON-LD global eindeutig sein soll oder nicht ([hier meine Stackoveflow-Frage dazu](https://stackoverflow.com/questions/76039394/does-id-in-json-ld-need-to-be-globally-unique)). Gegebenenfalls kann mir das jemand von euch beantworten :smile:

**Comment by kulla** [comment]
> Es sei denn vielleicht, die IRI-Specs sehen das so vor, das weiß ich nicht

Ich habe gelernt, dass IRIs nur eine Obermenge von URIs sind: https://fusion.cs.uni-jena.de/fusion/2016/11/18/iri-uri-url-urn-and-their-differences/ (URIs, die auch Nicht-ASCII unterstützen). In den Specs habe ich nichts dazu gefunden...

**Comment by acka47** [comment]
Siehe die Diskussion in #37, an deren Ende wir uns für Pattern-Matching entschieden haben. 

In UIs will mensch natürlich nicht in einem Filter die verschiedenen URIs zu einer Lizenz oder wahrscheinlich auch keine verschiedenen Versionen anzeigen, sondern eine Filterung nach Lizenzart oder auch Einschränlungen bei der Nachnutzung anbieten. Bei OERSI haben wir einen solchen Filter, den wir anhand des [license-Vokabulars](https://github.com/dini-ag-kim/license) umsetzen wollten, schon länger diskutiert, siehe https://gitlab.com/oersi/oersi-etl/-/issues/171. Wir haben die Umsetzung kürzlich vertragt, weil wir unsicher sind, ob das Lizenz-Vokabular der beste Ansatz ist.

**Comment by kulla** [comment]
@acka47 Dank dir für deine Antwort

Tatsächlich ist https://creativecommons.org/licenses/by-sa/4.0/deed.id die indonesische Version von CC-BY-SA 4.0 und es ist Zufall, dass es als erstes im schema.org Validator erscheint (siehe Antworten in https://stackoverflow.com/questions/76039394/does-id-in-json-ld-need-to-be-globally-unique).

Laut RDF scheint eher http://creativecommons.org/licenses/by-sa/4.0/ die kanonische URL / IRI zu sein:

```
https://creativecommons.org/licenses/by-sa/4.0/deed.id
  http://purl.org/vocab/frbr/core#translationOf
  http://creativecommons.org/licenses/by-sa/4.0/
```

Aber ja, ich sehe, dass es sehr schwierig ist für alle Lizenzvarianten (die bei CC bis 3.0 ja auch die länderspezifischen Lizenzen umfassen) kanonische URLs zu ermitteln. Dies können wir ggf in zukünftigen Versionen machen (als Empfehlung wäre es auch kein breaking change). Aktuell ist es das einfachste, wenn Konsumenten selbst ein Mapping der Lizenz-URL auf die eigene interne Lizenzstruktur vornehmen. Durch die aktuelle Spec werden ja bereits die URLs eingeschränkt. Deswegen schließe ich erst einmal das Issue.
