### ISSUE TITLE
`audience` unterscheidet sich zwischen Beispiel und Definition

### ISSUE THREAD

**Issue by kulla** [dini-ag-kim/amb#194]
Laut Spezifikation ist [`audience`](https://dini-ag-kim.github.io/amb/draft/#dfn-audience) eine Liste von Strings. Laut [JSON Schema](https://w3id.org/kim/amb/draft/schemas/audience.json) und im [Beispiel](https://dini-ag-kim.github.io/amb/draft/#full-example-higher-education) ist `audience` eine Liste von Objekten mit ID. Hier vermute ich, dass der Beschreibungstext entsprechend angepasst werden sollte (Ich bin dafür verlinkte JSON-LD Nodes konsequent als Objekt zu beschreiben).

**Comment by kulla** [comment]
Ergänzung: Laut https://schema.org/audience muss der Wert von `type` gleich https://schema.org/Audience sein

**Comment by acka47** [comment]
> Laut https://schema.org/audience muss der Wert von type gleich https://schema.org/Audience sein

Auch hier gilt: Das sind keine strikten Vorgaben. In schema.org heißt es "Values expected to be one of these types" bzw. im RDF noch weniger normativ: `sdo:rangeIncludes`. Ich sehe nicht, was gewonnen ist, wenn wir den Typ ergänzen.
