### ISSUE TITLE
Property "image" should allow objects

### ISSUE THREAD

**Issue by CodingDive** [dini-ag-kim/amb#199]
It's slightly inconsistent with https://dini-ag-kim.github.io/amb/draft/#trailer which allows objects.

In collaboration with @kulla, we are seeing that with images there is a possibility to add a lot of fields in the future. Like alt texts for improved accessibility, descriptions, having different images for different resolutions, etc.

I think we should address this before v1.0 as in the future going from string to object would be considered a breaking change.

**Comment by acka47** [comment]
> we are seeing that with images there is a possibility to add a lot of fields in the future. Like alt texts for improved accessibility, descriptions, having different images for different resolutions, etc.

You are probably right. However, we already support rich description of images as learning resources on their own that can also be part of another learning resource. See [example 3 in the spec](https://dini-ag-kim.github.io/amb/draft/#example-beschreibung-einer-in-eine-prasentation-eingebetteten-grafik).

For context: The `image` linked  is to be used as placeholder for the resource (right now, it says "Thumbnail der Ressource" in the spec). This is for example used by OERSI to generate the result list view, see e.g. https://oersi.org/resources?search=%22oer%22

**Comment by kulla** [comment]
@acka47 How about the case that we want to add metadata for the thumbnail in the future (like a license which differs from the main license). Then this would be a breaking change and I think we should try the spec in a way that we avoid breaking changes in the future.

**Comment by acka47** [comment]
> How about the case that we want to add metadata for the thumbnail in the future (like a license which differs from the main license). Then this would be a breaking change and I think we should try the spec in a way that we avoid breaking changes in the future.

As I said above, I agree and I am open to discuss this change. (Apparently, it sounded like I want to reject this, which is _not_ the case.) I just wanted to highlight how this is used and that we already have a way of adding metadata about images.

Re. breaking change: Though the spec is still a draft it is already implemented in production in different places, OERSI being only one of them. Accordingly, I have communicated in the past that we are dedicated to prevent any backward incompatible changes. So, though being a draft this will already break applications. 

This said, it is better to introduce any breaks as early on as we can _if_ they are really necessary. As one of the implementors, I'd be interested what @mirjan-hoffmann and @TobiasNx think of this. @mirjan-hoffmann would a change be beneficial for the OERSI data structure in the long run? @TobiasNx have you encountered any data sources that provide additional data about a resource image?

**Comment by mirjan-hoffmann** [comment]
I am not sure. Currently I don't know of any case in OERSI where other metadata than the image url would be available. There is also no request for it so far. Theoretically I can imagine that metadata (like a license) is set for an image, but I think a practical use case (in OERSI) is rather a rarity. It would be "nice to have" to be able to set this, if required, but it is not "really necessary" for OERSI atm.

**Comment by acka47** [comment]
Übrigens sind wir in diesem Ticket irgendwie aus Versehen im Englischen gelanget. ;-) Und dann stellt es sich auch noch als eines mit viel Diskussionsbedarf heraus...

**Comment by kulla** [comment]
Protokoll aus dem heutigen Sprint:

* Boris: Im Merge zweier Datenbanken hatten wir den Fall, dass es bei einem Bildungsinhalt mehrere Previews gab (mit unterschiedlichen Brandings)
* Manuel: In WLO aktuell nur ein Thumbnail im Datenmodell gespeichert, aber zusätzliche Infos wie Größe und Breite wird gespeichert / Mehrere Thumbnails nicht notwendig
* Carl: In SODIX ein Thumbnail im Datenmodell
* Boris: Lizenz als zusätzliche Information für Thumbnails notwendig
* Kulla: Mit einem Objekt haben Bildungsanbieter die Möglichkeit zusätzliche Informationen zum Thumbnail zu speichern (selbst wenn es nicht in unserer Spec steht)

**Ergebnis:** Wir empfehlen die Änderung von `string` in `object` -> diesen Vorschlag geben wir so in das nächste Treffen rein

**Comment by acka47** [comment]
Wie angekündigt, habe ich das ins OERSI-Treffen mitgenommen. Das Ergebnis:

- Wir sehen immer noch nicht die Notwendigkeit, ein Objekt bei `image` zu erlauben, werden uns aber auch nicht sperren, wenn andere das anders sehen.
- Als Datenkonsument ist es für uns unproblematisch, wenn zukünftig Datenquellen `image`+ Objekt liefern,
- Als Datenanbieter halten wir zu diesem Zeitpunkt eine Anpassung des OERSI-JSONs für nicht sinnvoll. Ein solcher API-Break würde eine Menge Anpassungen bei OERSI und den Konsumenten der OERSI-API bedeuten, die zum jetzigen Zeitpunkt durch keinerlei zusätzlichen Nutzen gerechtfertigt würden. Sollten in Zukunft Anfragen von Seite der OERSI-API-Konsument:innen nach Zusatzinformationen zu den Thumbnails kommen, werden wir uns dieser Frage ggf. erneut widmen.

**Comment by acka47** [comment]
Aus dem vorherigen Kommentar folgt, dass die einzige mögliche Anpassung der Spec zur Ermöglichung eines Objekts bei `image` ist, beide Varianten zu erlauben (`string` und `object`).

**Comment by lummerland** [comment]
Der Vollständigkeit halber noch eine Ergänzung aus dem WLO Kontext, die ich gerade nochmal mit unseren ExpertInnen recherchiert habe: 

Wir bilden zwar Bilder über ein Objekt ab, die zusätzlichen Daten wie Größe oder mimetype holen wir uns jedoch selbst über einen HTTP-Request auf die Bild-URL oder andere Mechanismen. Wenn statt einem String nun Objekte geliefert werden würden hätten wir zwar wenig Arbeit mit der Änderung, allerdings auch keinen Mehrwert, die Daten würden wir nicht verwerten. 

Aus Sicht von Konsumenten wäre für uns relevant, dass die URL als wichtigstes Metadatum eindeutig identifiziert und extrahiert werden kann. Eine Lösung, bei der man als Konsument erst prüfen muss, was für einen Typ Daten man da vor sich hat (`string` und `object` erlauben), sehen wir da eher kritisch.

**Comment by acka47** [comment]
Das werden wir vorerst nicht anpassen, weil der hypothetische Bedarf einigen Brüchen bei bestehenden APIs und Clients gegenübersteht. Closing.
