### ISSUE TITLE
`isBasedOn` unterscheidet sich von `isPartOf`

### ISSUE THREAD

**Issue by kulla** [dini-ag-kim/amb#215]
Mir sind größere Unterschiede zwischen https://dini-ag-kim.github.io/amb/draft/schemas/isBasedOn.json und https://dini-ag-kim.github.io/amb/draft/schemas/isPartOf.json aufgefallen:

* Die Liste der required-Attribute ist unterschiedlich
* Sollten Properties wie `type`, `id` und `name` verlinkt werden?

Ich vermute, dass beide Schemas ähnlich sein sollen. Welche von beiden Schemas ist die aktuellere?

**Comment by acka47** [comment]
Wir sollten bei denen m.E. einfach rekursiv https://dini-ag-kim.github.io/amb/draft/schemas/schema.json referenzieren, weil hier im Prinzip eine komplette Ressourcenbeschreibung angegeben werden kann. Oder?

**Comment by bokahama** [comment]
Ich folge der Argumentation von Manuel und würde bei has part / is part of würde ich nicht aufblähen. Jedoch sollten wir bei Relationen wie *isVersionOf* genauso umfangreich wie bei *isBasedOn* sein

**Comment by kulla** [comment]
Ergebnis der heutigen Diskussion: Die aktuelle Definition passt so und @oellers konnte gut den Gedanken dahinter erklären. Mit #238 kann dieses Ticket geschlossen werden.

Eine Verbesserung im Anschluss an den Kommentar von @acka47 könnte man https://github.com/dini-ag-kim/amb/issues/241 umsetzen, aber das ist kein Thema, welches man vor der 1.0 machen muss...

**Comment by bokahama** [comment]
Ich meinte es perspektivisch, als Erinnerungsposten – habe es in einem anderen Schema schon mal als Wert gesehen
