### ISSUE TITLE
Update settings to delete branch after merge

### ISSUE THREAD

**Issue by kulla** [dini-ag-kim/amb#222]
Kann jemand mit entsprechenden Rechten (ggf @acka47) unter https://github.com/dini-ag-kim/amb/settings einstellen, dass Branches nach einem Merge gelöscht werden? Setting ist dieses:

![2023-04-25-105346_596x144_scrot](https://user-images.githubusercontent.com/1327215/234226024-72ab1f6c-8e32-45e5-8a74-d91aadecaf0e.png)

So sammeln wir nicht viele offene branches unter https://github.com/dini-ag-kim/amb/branches. Danke!

**Comment by lummerland** [comment]
Done :)
