### ISSUE TITLE
Formatter hinzufügen

### ISSUE THREAD

**Issue by kulla** [dini-ag-kim/amb#223]
Ich würde gerne https://www.npmjs.com/package/prettier diesem Projekt hinzufügen, damit alle JSON-Dateien automatisch formatiert werden. Gibt es Widersprüche dagegen? Gibt es Wünsche welches Build-Tool verwendet werden soll? `npm` oder `yarn`?

**Comment by sroertgen** [comment]
Gute Idee. Ich arbeite meist mit `npm`, bin da aber leidenschaftslos. Wenn es entsprechend dokumentiert ist, sollte es keine Probleme geben
