### ISSUE TITLE
Fehler auf der Webseite: Markdown nicht zum html gemacht

### ISSUE THREAD

**Issue by hugotiburtino** [dini-ag-kim/amb#226]
![image](https://github.com/dini-ag-kim/amb/assets/45924645/ea5b05d8-b0cd-4ede-af4f-75e8e6cecdfd)
![image](https://github.com/dini-ag-kim/amb/assets/45924645/bdec7efb-1c87-4609-88fd-1b8486696437)

screenshots: 15.05.2023 9 Uhr 15

**Comment by sroertgen** [comment]
Kann ich bestätigen.

Hat vmtl was mit #224 zu tun (?) 

@kulla @acka47 

Hattet ihr das HTML vorher lokal getestet? Hat das funktioniert?

**Comment by sroertgen** [comment]
Working now again with https://github.com/dini-ag-kim/amb/commit/9a940640ebc733e567031ab509d6f48220514a76

**Comment by acka47** [comment]
Ja, das liegt an dem Formatter. Ich habe den entsprechenden Commit rückgängig gemacht (https://github.com/dini-ag-kim/amb/commit/9a940640ebc733e567031ab509d6f48220514a76), so dass es jetzt wieder funktioniert. Dieses Ticket schließe ich dann und die Anpassung der Formatters erledigen wir in #227 .
