### ISSUE TITLE
Erlaubtes OEH-Vokabular für den learningResourceType korrigieren

### ISSUE THREAD

**Issue by lummerland** [dini-ag-kim/amb#243]
Aktuell sind neben Werten aus dem HCRT-Vokabular noch die Werte aus http://w3id.org/openeduhub/vocabs/learningResourceType/ erlaubt. Allerdings wird dieses, von **LOM** übernommene Vokabular in _WirLernenOnline_ nur noch in Datenexporten verwendet. Für die Metadaten selbst, die Suche und das UI wurde das Vokabular mal umgestellt auf ein deutlich erweitertes und eine davon abgeleitete komprimierte Variante, die nicht mehr 1:1 den LRT aus LOM abbilden.

Das umfangreiche Vokabular: https://vocabs.openeduhub.de/w3id.org/openeduhub/vocabs/new_lrt/index.html bzw. die SKOS Datei: https://github.com/openeduhub/oeh-metadata-vocabs/blob/master/new_lrt.ttl

Das aus Gründen der Performance und Usability aggregierte Vokabular: https://vocabs.openeduhub.de/w3id.org/openeduhub/vocabs/new_lrt_aggregated/index.html

Vor der Finalisierung der 1.0 sollte m.E. auf das aktuelle Vokabular umgestellt werden. Auf welches der beiden können wir gerne diskutieren. In Oersi wird m.W. nur HCRT verwendet, so dass ich eigentlich keine Probleme erwarten würde wenn wir den möglichen Wertebereich anpassen.

**Comment by oellers** [comment]
[Mapping Liste auf HCRT (ohne new_lrt_aggregated)](https://gitlab.com/oersi/oersi-etl/-/blob/master/data/maps/OEH_LRT-HCRT.tsv)

**Comment by carlschuurbiers** [comment]
Eine Anpassung/Update der Lernressourcetypen im LOM-DE Standard ist gerade in Arbeit in der AGMuD (Arbeitsgruppe Mediendistribution und Dokumentation). Es wäre gut noch ein bisschen abzuwarten was da beschlossen wird. Die Diskussion dort ist noch im Gange.

**Comment by lummerland** [comment]
Ich glaube, hier gibt es ein Mißverständnis. In dem Ticket geht es nur darum, ein im AMB referenziertes (WirLernenOnline-)Vokabular durch ein anderes auszutauschen. Es sind beides LRTs, nur das aktuell im AMB referenzierte ist veraltet. Eine Überarbeitung der LRTs grundsätzlich ist m.E. ein anderes Thema und hier erstmal nicht relevant. Nach der Überarbeitung der LRTs und der Entscheidung, die hier im AMB zu verwenden müssen wir hier nochmal aktiv werden, das stimmt. Aber dann machen wir dafür wieder ein Ticket auf.
