### ISSUE TITLE
learningResourceType Regex-Pattern nicht korrekt

### ISSUE THREAD

**Issue by JensWinter** [dini-ag-kim/amb#257]
Hallo!

mir ist aufgefallen, dass das Pattern für learningResourceType nicht ganz korrekt ist. Das Regex-Pattern prüft nur für HCRT, of die id-Werte korrekt *beginnen*. Nicht für Openeduhub.

Das wird nicht als Fehler erkannt:
```
{
   "id": ""xxxhttp://w3id.org/openeduhub/vocabs/new_lrt/588efe4f-976f-48eb-84aa-8bcb45679f85""
}
```

**Comment by acka47** [comment]
Danke für den Hinweis, Jens. Wir werden das bei der heutigen Publikation der offiziellen Version bverücksichtigen, siehe https://github.com/dini-ag-kim/amb/pull/256.
