### ISSUE TITLE
Using tags / releases in the github repository

### ISSUE THREAD

**Issue by AOphagen** [dini-ag-kim/amb#259]
Are you planning to use tags and releases in your repository, now the first version has been finalized?

I can reach the currently latest version permanently by the link https://dini-ag-kim.github.io/amb/20231019, but no tag in the repository refers to it, so I cannot pin my implementation against a fixed AMB 'version'?

Also, the link to the JSON schema on [that page]( https://dini-ag-kim.github.io/amb/20231019) still leads to https://w3id.org/kim/amb/draft/schemas/schema.json instead of https://dini-ag-kim.github.io/amb/20231019/schemas/schema.json, so there is a mistake in that page, I think.

I'd like to regard this issue as a proposal for _discussion_ and remediation of the situation...

**[Update]**
In the file with the path https://dini-ag-kim.github.io/amb/20231019/schemas/schema.json, all the entries are also links to **draft**, not to **20231019 ??**

**Comment by AOphagen** [comment]
Maybe I'll make a pull request of this after all. I see that all the files are there in the folder 20231019?

**Comment by AOphagen** [comment]
Giz a moment, PR is in the pipe

**Comment by AOphagen** [comment]
Feel free to use that - it was just batch replace. did I understand the principle correctly?

**Comment by acka47** [comment]
Thanks, @AOphagen , I merged your commit (though I ran into some git behaviour I did not understand on the way but the commit history looks fine now). Also corrected one minor error we have been having for some time now with 825520b63719e7cfd5f27dcaf0b15f8e36c0f29e. Closing.

**Comment by acka47** [comment]
We haven't answered the original question re. tag. Reopening.

BTW, the StoeberSpecs process already made clear to check schema references etc. see https://github.com/dini-ag-kim/stoeberspecs#publikation-einer-neuen-version-mit-respec but I did not read it thoroughly...

**Comment by acka47** [comment]
I tagged the current status (being optimistic that by now we have _really_ made all changes for 20231019 ;-) ) see https://github.com/dini-ag-kim/amb/tags . Thanks for the request, @AOphagen . Please close the issue if everything looks as expected.

**Comment by acka47** [comment]
Also added a release: https://github.com/dini-ag-kim/amb/releases/tag/20231019 (If we close this issue today it will be part of the linked issue list.)

**Comment by AOphagen** [comment]
This is the very last occurence of the word 'draft' and that is correct there: https://github.com/dini-ag-kim/amb/blob/16e0a451af214ce9ac4d7a84fe8268cafca0107d/20231019/index.html#L150

All done. Thank y'all!

**Comment by AOphagen** [comment]
> I tagged the current status (being optimistic that by now we have _really_ made all changes for 20231019 ;-) ) see https://github.com/dini-ag-kim/amb/tags . Thanks for the request, @AOphagen . Please close the issue if everything looks as expected.

Here the comparison should be <= 2023-10-23 or < 2023-10-24 @acka47 
https://github.com/dini-ag-kim/amb/releases/tag/20231019
