### ISSUE TITLE
AMB-Spec zerschossen? 

### ISSUE THREAD

**Issue by trostorff** [dini-ag-kim/amb#270]
Hey! Die Seite https://dini-ag-kim.github.io/amb/latest/ scheint kaputt zu sein, der Test mit drei verschiedenen Browsern ergab die gleiche zerschossene Seite. Die Seitenleiste links fehlt und die Struktur ist sehr schwer zu erkennen. Fehler bei mir oder beim Server? Lg, *

![image](https://github.com/dini-ag-kim/amb/assets/168189092/7f29d709-7916-4049-998a-56b46567c48b)

**Comment by lummerland** [comment]
![2024-06-07_11-25](https://github.com/dini-ag-kim/amb/assets/2832257/178c7b51-1f7d-478a-8bce-ba9eb11c80de)
Vielleicht ist das hier die Ursache, da scheint eine JS-Datei nicht gefunden zu werden.

**Comment by trostorff** [comment]
es scheint auf jeden fall auch noch andere seiten zu betreffen, z.B. das LOM unter https://dini-ag-kim.github.io/hs-oer-lom-profil/latest/

**Comment by acka47** [comment]
Danke für die Meldung. Ja, das ist das Problem, @lummerland . Wir nutzen für die Spezifikation die Software ReSpec, die bisher unter https://github.com/w3c/respec gepflegt und gehostet wurde, siehe https://github.com/dini-ag-kim/stoeberspecs/commit/b69f80c34c6e8048a023b20bcb150c5f1196f5c6. Dort wurde extra ein gesondertes DINI.Profil angelegt

Nun wurde das Repo – ohne eine Ankündigung, die ich mitbekommen hätte – nach https://github.com/speced/respec umgezogen. Die respec.dini.js liegt dementsprechend nun unter https://speced.github.io/respec/builds/respec-dini.js . Ich mache gleich einen Pull Request umd das zu korrigieren.

**Comment by acka47** [comment]
Ich habe das auch mal per Issue im ReSpec-Repo gemeldet: https://github.com/speced/respec/issues/4729

**Comment by acka47** [comment]
Der PR ist gemergt, die Seiten neu gebaut und das Ticket bereits automatisch geschlossen. Sieht auch alles gut aus: https://dini-ag-kim.github.io/amb/latest/

Danke nochmal für die Meldung, @trostorff !

**Comment by trostorff** [comment]
@acka47 danke fürs fixen!
