### ISSUE TITLE
Ergänze Liste von AMB-Implementierungen

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/amb#279]
Im gestrigen [Treffen mit DALIA](https://metadaten.community/t/dalia-kim-treffen-zum-dif-und-amb/430) kam die Frage auf, welche Anwendungen bereits das AMB implementieren. Ich denke, es wäre gut, wenn wir gemeinsam – evtl. am besten in einer separaten Markdown-Datei in diesem Repo? – eine entsprechende Liste erstellen und pflegen würden.

**Comment by kulla** [comment]
Meine Liste soweit

* Serlo: https://en.serlo.org/metadata
* WLO
* e-teaching
* MeinBildungsraum, https://www.meinbildungsraum.de/

**Comment by sroertgen** [comment]
- OERSI

**Comment by acka47** [comment]
Erledigt mit #280. Ich schließe das Ticket.
