### ISSUE TITLE
Anpassung des Namens und der URIs des Profils

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/amb#69]
Momentan ist der Name "LRMI-Profil" (und die URI der aktuellen Version `https://w3id.org/kim/lrmi-profile/latest/`). Einige Dinge sprechen gegen diesen Namen:

- Das Profil basiert nicht vollständig auf LRMI, sondern nutzt auch SKOS und schema.org-Properties und -Klassen, die nicht bei LRMI auftauchen (z.bB. `isPartOf`, `hasPart`).
- Der Name ist nicht besonders sprechend. Besser wäre es, wenn der Name zumindest einige der folgenden Aspekte enthalten oder andeuten würde:
   - Es ist ein Metadatenprofil zur Beschreibung von Lehr- und Lernressourcen.
   - Es ist ein Profil für den deutschsprachigen Raum.
   - Es deckt die Bereiche Hochschule und allgemeinbildende Schulen ab.
 
Die momentane Zusammenfassung in der Spezifikation lautet entsprechend:

> Ein Metadatenprofil für die Beschreibung von OER mit Fokus auf den deutschsprachigen Raum. Es basiert hauptsächlich auf [schema.org] bzw. Learning Resource Metadata Initiative [LRMI] und nutzt dazu Teile von Simple Knowledge Organization System [SKOS].

(Seitennotiz: Vielleicht sollten wir da das "OER" in der Zusammenfassung durch "Lehr- und Lernressourcen" übersetzen, da sich das Profil ja auch für die Beschreibung nicht-offener Ressourcen eignet.)

**Comment by acka47** [comment]
@TobiasNx und ich haben eben besprochen, dass wir zumindest die URI (`lrmi-profile`) nicht anpassen werden, allenfalls den Titel der HTML Spec.

**Comment by acka47** [comment]
Hier ein paar Ideen als Anstoß.

- Bildungsbereichübergreifendes Metadatenprofil für Lehr- und Lernressourcen
- Allgemeines Metadatenprofil für Bildungsressourcen

Wollen wir eigentlich auch ein Akronym?

**Comment by sroertgen** [comment]
Hallo zusammen,

ich finde "Allgemeines Metadatenprofil für Bildungsressourcen" gut, da es nicht ganz so sperrig klingt wie "bildungsbereichübergreifend".

Akronym fände ich auch nicht schlecht...

**Comment by acka47** [comment]
Ich hab den Namen jetzt schonmal angepasst mit 6ddf6b953b917b2c289bf10f894aa26240f0d75a.

**Comment by acka47** [comment]
Ich denke, wir sollten dann auch den Repo-Namen anpassen ("amb") und die W3ID (https://w3id.org/kim/amb/draft/). Einen extra Redirect für das Profil gibt es noch nicht, siehe https://github.com/dini-ag-kim/w3id.org/blob/master/kim/.htaccess, so dass da nichts angepasst werden muss.
