### ISSUE TITLE
Problem mit nicht-escaptem HTML in Markdown-Code-Blöcken

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/amb#73]
Das Problem tritt bei URIs mit spitzen Klammern in HTTP-Header-Beispielen auf. Input Beispiel:

https://github.com/dini-ag-kim/lrmi-profile/blob/7fc3b7832281384598e37d3b9235aff127345113/draft/index.html#L204-L207

HTML-Sicht:

![image](https://user-images.githubusercontent.com/160292/111476618-9d2ab800-872e-11eb-92f0-5ee827204097.png)

Es könnte sich um das ein ähnliches Problem wie https://github.com/w3c/respec/issues/3005 handeln, das Anfang Juli 2020 behoben wurde. Müssen wir das vielleicht was im DINI-Respec-Profil nachziehen, @sebastian-meyer ?

**Comment by sroertgen** [comment]
According to https://github.com/w3c/respec/issues/4077#issuecomment-1067519160 this should work:

<pre class="nolinks HTTP">
HTTP/1.1 200 OK
Content-Type: application/ld+json
Link: &lt;https://w3id.org/kim/lrmi-profile/2021mmdd/>; rel="profile"
</pre>

**Comment by sroertgen** [comment]
should we maybe document this solution somewhere? @acka47
