### ISSUE TITLE
Ergänzen Felder zur Beschreibung von Videoinhalten

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/amb#90]
Einige für Videoinhalte relevante Angaben werden bereits in #82 besprochen. Hier soll es um die videospezifischen Felder gehen. Hier zunächst mal eine Sammlung von video-relevanten Angaben mit Angabe von existierenden schema.org-Properties, wenn vorhanden:

- Spielzeit/Videolänge: [`sdo:duration`](https://schema.org/duration)
- ~~Altersbeschränkungen: [`sdo:typicalAgeRange`](https://schema.org/typicalAgeRange) oder [`sdo:audience`](https://schema.org/audience) -> [`sdo:PeopleAudience`](https://schema.org/PeopleAudience) -> [`sdo:requiredMinAge`](https://schema.org/requiredMinAge)~~  -> verschoben nach #140 
- Untertitel: [`sdo:caption`](https://schema.org/caption)
-  ~~URL zum Einbetten eines Videos: [`sdo:embedUrl`](https://schema.org/embedUrl)~~ (erledigt mit #92)

Hier ein Beispiel als Diskussionseinstieg:

```json
{
  "@context": [
    "https://w3id.org/kim/lrmi-profile/draft/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "type": [
    "LearningResource",
    "MediaObject"
  ],
  "id": "https://mediathek.hhu.de/watch/93a697c4-cbe9-475d-b66b-0db6cebc35c0",
  "title": "Begrüßung zum Modul \"Rechnernetze, Datenbanken und Betriebssysteme\"",
  "duration": "PT19M17S",
  "caption": {
    "id": "https://example.org/subs.vtt",
    "type": "MediaObject",
    "encodingFormat": "text/vtt"
  },
  "creator": {
    "name": "Martin Mauve "
  },
  "image": "https://mediathek.hhu.de/thumbs/93a697c4-cbe9-475d-b66b-0db6cebc35c0/thumb_000.jpg",
  "audience": {
    "type": [ "PeopleAudience"],
    "requiredMinAge": 0
  },
  "typicalAgeRange": "16-99",
  "encoding":[
    {
      "type": "MediaObject",
      "encodingFormat":"video/mp4",
      "contentSize":"65MB",
      "contentUrl":"https://mediathek.hhu.de/download/93a697c4-cbe9-475d-b66b-0db6cebc35c0/mp4/v_1_100",
      "description": "hohe Qualität mit Abmessungen 1280 x 720 Pixel",
      "embedUrl":"https://mediathek.hhu.de/watch/93a697c4-cbe9-475d-b66b-0db6cebc35c0"
    },
    {
      "type": "MediaObject",
      "encodingFormat":"video/webm",
      "contentSize":"112MB",
      "contentUrl":"https://mediathek.hhu.de/download/93a697c4-cbe9-475d-b66b-0db6cebc35c0/webm/v_2_100",
      "description": "hohe Qualität mit Abmessungen 1280 x 720 Pixel"
    }
  ]
}
```

**Comment by acka47** [comment]
Im ORCA-Kontext kam noch die Frage zur Videoauflösung auf.Ich schrieb dazu in einem [ORCA-internen Ticket](https://git.noc.ruhr-uni-bochum.de/orca/portalaufbau/-/issues/94#note_78505):

> In schema.org gibt es unter https://schema.org/VideoObject [`videoFrameSize`](https://schema.org/videoFrameSize) und [`videoQuality`](https://schema.org/videoQuality). Beides könnte verwendet werden, evtl. wäre es auch sinnvoll ein kontrolliertes Vokabular (low, medium, high quality o.ä.) zu publizieren, das zusammen mit `sdo:videoQuality` verwendet wird.

**Comment by s-prepens** [comment]
Ergänzend dazu: 
Erweiterung um ein Feld, um Untertitel für Videos so abzubilden, dass sie separat von der Videodatei aufrufbar/herunterladbar sind?

**Comment by acka47** [comment]
> Erweiterung um ein Feld, um Untertitel für Videos so abzubilden, dass sie separat von der Videodatei aufrufbar/herunterladbar sind?

Das ist oben bereits abgedeckt mit https://schema.org/caption, z.B.:

```json
  "caption": {
    "id": "https://example.org/subs.vtt",
    "type": "MediaObject",
    "encodingFormat": "text/vtt"
  }
```

@s-prepens Wenn das in Orca jetzt benötigt wird, sollten wir das Ticket wohl mal angehen. Ich denke aber, dass es unbedenklich ist, wenn das in ORCA auch vorher schon entsprechend umgesetzt wird.

**Comment by acka47** [comment]
Im [heutigen Treffen](https://pad.gwdg.de/s/2022-03-08-kim-oer#Erg%C3%A4nzen-Felder-zur-Beschreibung-von-Videoinhalten) wurden folgende Anforderungen zur Ergänzung von `caption` gesammelt:

- Transskription für Audio sollte auch abgedeckt werden 
- Der Bezug zu Bildunterschriften (engl. "caption") sollte geklärt werden und diese entweder mit abgedeckt oder `caption` davon klar abgegrenzt werden. Verwandte Frage: Wie unterscheiden sich bei Bildern `name`, `description` und – `caption`?

**Comment by acka47** [comment]
Bei den Untertiteln muss auch die Sprache mit angegeben werden, d.h. `caption` sollte einen Array erwarten und das Feld `inLanguage` erlauben/erfordern, z.B.:

```json
{
   "caption":[
      {
         "id":"https://example.org/subs-de.vtt",
         "type":"MediaObject",
         "encodingFormat":"text/vtt",
         "inLanguage":"de"
      },
      {
         "id":"https://example.org/subs-en.vtt",
         "type":"MediaObject",
         "encodingFormat":"text/vtt",
         "inLanguage":"en"
      }
   ]
}
```
