### ISSUE TITLE
Kostenfreie Nutzung/Zugang ausweisen?

### ISSUE THREAD

**Issue by TobiasNx** [dini-ag-kim/amb#91]
Seit wir das Profil auch erweitern um sowohl OER als auch nicht OER abzubilden, sollten wir meiner Meinung nach auch die kostenfreie Nutzbarkeit/Zugang einer Ressource ausweisen. Es gibt Nicht-OER, die aber kostenfrei nutzbar sind. Das wird aber durch die gegenwärtigen Metadaten nicht abbildbar.

Daher mein Vorschlag, wir sollten dies in den Metadaten abbilden:

Möglich wäre zum Beispiel das Feld:

`conditionsOfAccess` (https://schema.org/conditionsOfAccess)

**Comment by TobiasNx** [comment]
Ich schlage einmal folgendes Vokabular für `conditionsOfAccess` vor:

```
Accessible without login
Accessible without login + Login for additional features
Accessible without login + Pay for additional features
Login required
```

Für `isAccessibleForFree` - boolean:
```
true
false
```

**Comment by TobiasNx** [comment]
Alternative:
No login required
Login for additional features required
Login required

**Comment by sroertgen** [comment]
> Ich schlage einmal folgendes Vokabular für `conditionsOfAccess` vor:
> 
> ```
> Accessible without login
> Accessible without login + Login for additional features
> Accessible without login + Pay for additional features
> Login required
> ```

Bezahlinformationen würde ich hier raus lassen. So etwas ließe dann eher über ein Attribut wie `price` abbilden (e.g. https://schema.org/price).

**Comment by axel-klinger** [comment]
Wie wäre es mit 

```
Open Access
Closed Acces with Open Registration
Closed Access
```

**Comment by TobiasNx** [comment]
> Wie wäre es mit
> 
> ```
> Open Access
> Closed Access with Open Registration
> Closed Access
> ```
Meiner Meinung nach sprechen zwei Dinge dagegen:
1) Open Access ist mit ziemlich viel semantischen Balast versehen.
2) Müssen wir auch solche kostenlosen Ressourcen abbilden können, die nicht Open Access sind und auch keine Registrierschranke haben

>      
Bezahlinformationen würde ich hier raus lassen. So etwas ließe dann eher über ein Attribut wie price abbilden (e.g. https://schema.org/price).

Da stimme ich zu, das schien mir auch der strittigste Punkt.

**Comment by TobiasNx** [comment]
> Ich schlage einmal folgendes Vokabular für `conditionsOfAccess` vor:
> 
> ```
> Accessible without login
> Accessible without login + Login for additional features
> Login required
> ```
> oder 
```
No login required
Login for additional features required
Login required

```

> Für `isAccessibleForFree` - boolean:
> 
> ```
> true
> false
> ```

**Comment by acka47** [comment]
Im heutigen Treffen haben wir uns darauf geeinigt, erstmal mit einem einfachen Registrierung: ja/nein-Ansatz zu beginnen. Um das erweiterbar zu machen, werden wir aber nicht mit booleschen Werten arbeiten, sondern mit einem kontrollierten Vokabular, das am Anfang zunächst die zwei Werte enthält.

**Comment by kulla** [comment]
Aus Perspektive eines OER-Repositories (Serlo) wäre es gut, wenn die Angabe von `isAccessibleForFree: true` bei OER ausreicht. Dieses Attribut wollen wir eh als schema.org Attribut für Suchmaschinen aufnehmen. Erst wenn `isAccessibleForFree: false` ist, ist IMHO eine differenzierte Angabe notwendig.

**Comment by TobiasNx** [comment]
@acka47 kannst du dir mal meine Vorschläge anschauen und die PRs fertig machen?

**Comment by acka47** [comment]
> Aus Perspektive eines OER-Repositories (Serlo) wäre es gut, wenn die Angabe von isAccessibleForFree: true bei OER ausreicht. 

Ich denke, dass passt leider nicht. Wenn ich das richtig sehe, wird das "free" im Sinne von "free beer" benutzt.

> Dieses Attribut wollen wir eh als schema.org Attribut für Suchmaschinen aufnehmen. Erst wenn isAccessibleForFree: false ist, ist IMHO eine differenzierte Angabe notwendig.

Die Kombination von `"isAccessibleForFree": true` und `"conditionsOfAccess": "registration required"` wäre m.E. durchaus möglich und ich sehe nicht, dass wir das anders definieren können/sollten.

**Comment by acka47** [comment]
Aus https://github.com/dini-ag-kim/amb/issues/91#issuecomment-964127091:

> Im heutigen Treffen haben wir uns darauf geeinigt, erstmal mit einem einfachen Registrierung: ja/nein-Ansatz zu beginnen ([Notizen](https://pad.gwdg.de/s/2021-11-09-kim-oer#OER-Zugangsstatus)). Um das erweiterbar zu machen, werden wir aber nicht mit booleschen Werten arbeiten, sondern mit einem kontrollierten Vokabular, das am Anfang zunächst die zwei Werte enthält. 

Aus https://github.com/dini-ag-kim/amb/pull/124#pullrequestreview-864617853:

> Ein eigenes Repo für ein so kleines Vokabular ist wahrscheinlich etwas Overkill. Mein Vorschlag: Wir legen ein Repo namens `value-lists` an, in das wir solche kleinen Vokabulare packen. Was meinen andere?

**Comment by acka47** [comment]
Erledigt mit #124 und #125.
