### ISSUE TITLE
Ergänze "license" als mögliches Feld in "isPartof" u. "hasPart"

### ISSUE THREAD

**Issue by TobiasNx** [dini-ag-kim/amb#93]
Mir ist gerade am Beispiel https://github.com/dini-ag-kim/lrmi-profile/blob/main/draft/examples/valid/parts.json aufgefallen, dass dort `"license"` in `"isPartOf"` noch als string hinterlegt ist. Wir sollten unser "license"-Schema als mögliche Feld-Option referenzieren, dann würde auch in den Beispielen `"license"`-Angaben invalide sein.

**Comment by acka47** [comment]
Wird geschlossen, weil das Thema in #241 hinreichend und generisch behandelt wird.
